### ISSUE TITLE
Feature: publish price feeds

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#1131]
Some assets don't need to publish price frequently, it would be useful if price feed can be published from GUI.

**Comment by startailcoon** [comment]
I believe this would be a good feature to the UI. It would require some updates to bitsharesjs as well.

## Tasks

- [ ] View a `post price` form on an assets page.
- [ ] Visible only for users that are allowed to post prices
- [ ] Add capability to bitsharesjs if required

**Comment by wmbutler** [comment]
Needs UX submitted first.

**Comment by startailcoon** [comment]
UX should be part of #1629 #1604

**Comment by startailcoon** [comment]
Releasing this for now

**Comment by svk31** [comment]
Nothing is needed in bitsharesjs

**Comment by abitmore** [comment]
@svk31 I noticed that on the image, MCR is 175 but not 1750, MSSR is 110 but not 1100, please make sure the data is correct. By the way, perhaps better to use the same style used elsewhere:

![image](https://user-images.githubusercontent.com/9946777/43423364-8aed2696-944c-11e8-89f8-9943b6516507.png)

**Comment by svk31** [comment]
It's being displayed as % in the current price feed table so I kept it the same here, but I can change both to be ratios of 1.x if that makes more sense.

**Comment by startailcoon** [comment]
@svk31 just make sure it's defined, since feed publishers are used to the first type you had. Either is fine I guess, as long as its understandable.

**Comment by abitmore** [comment]
@wmbutler I believe this has been done already.

**Comment by wmbutler** [comment]
Cool, I guess @svk31 should close it if he agrees.
