### ISSUE TITLE
UI changes for next bitshares-core hardfork release

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#1493]
This is a place holder for all tasks related to next hardfork release. We have 2 months to get UI ready.

* New testnet release will be available in this week, and hard fork will occur in one or two weeks.
* Mainnet release will be available one month later, and hard fork time will be scheduled to another month later.

UI changes (ordered by workload/priority):
- [x] [BSIP38](https://github.com/bitshares/bsips/blob/master/bsip-0038.md) Allow user to update  `target_collateral_ratio` option on short positions in UI (#1575)
- [x] [BSIP38](https://github.com/bitshares/bsips/blob/master/bsip-0038.md) Render order book according to new `target_collateral_ratio` option on short positions (#1576)
- [x] [BSIP29](https://github.com/bitshares/bsips/blob/master/bsip-0029.md) changed operation to update issuer of an asset (#1596)
- [x] [BSIP27](https://github.com/bitshares/bsips/blob/master/bsip-0027.md) new operation for asset issuers to claim BTS from fee pool (this is not to claim accumulated fees) (https://github.com/bitshares/bitshares-ui/issues/1598)
- [x] [BSIP30](https://github.com/bitshares/bsips/blob/master/bsip-0030.md) allow updating of short position even when in margin call territory (E.G. allow users to set collateral ratio to less than 175% under certain circumstances) (#1577)
- [x] [BSIP37](https://github.com/bitshares/bsips/blob/master/bsip-0037.md) asset name can be ended with a number (no longer only letters)(#1566)

Other pages needed to change for compatibility:
- [x] account activities (#1547)
- [x] block explorer (#1547)
- [x] fee schedule (#1784)

**Comment by abitmore** [comment]
@wmbutler these are tasks, not proposed feature.

**Comment by wmbutler** [comment]
@abitmore my definition of a feature is something that was not present before but is to be added. A task refers to housekeeping.

**Comment by svk31** [comment]
https://github.com/bitshares/bitsharesjs/commit/743b4391955a95ae4d976bc6dd24cc8e4e0ec9be

**Comment by abitmore** [comment]
> until each is broken into its own issue and added to a sprint.

Please help make it.

**Comment by sschiessl-bcp** [comment]
@wmbutler @startailcoon 
This needs grooming and prioritizing. Especially BSIP38, which should probably be included in a hotfix.

**Comment by startailcoon** [comment]
BSIP 38 is already tagged `high priority`. None has shown interest in working on the UI so far. I've taken the task and will work on whatever I can/have time with this weekend.

**Comment by startailcoon** [comment]
BSIP 29 was assigned to gibbsfromncis, but it's still in progress.

**Comment by abitmore** [comment]
@gibbsfromncis is on vacation.

**Comment by startailcoon** [comment]
he is, so the tasks of his are free for others to work on.

**Comment by gibbsfromncis** [comment]
@abitmore I'm in vacation and I've posted a message in each issue that anyone can assign it if want. 

Today I've added `free to assign` title. Maybe this will help to close these issues before I come back.

**Comment by svk31** [comment]
@abitmore The global object doesn't contain any fee information for the new operations as far as I can tell, so there's no way for us to display fee information for them. The current_fees array stops at operation 43:

![image](https://user-images.githubusercontent.com/6890015/44252597-f50e8480-a1fc-11e8-9f71-049f5866ef63.png)

**Comment by svk31** [comment]
I've added the relevant operations to the page, but until they show up in the global object no info will be displayed.

**Comment by abitmore** [comment]
@svk31 before the committee explicitly set fees for those operations, they are implicitly applied as follows:
* bid_collateral_operation -> call_order_update_operation
* asset_update_issuer_operation -> asset_update_operation
* asset_claim_pool_operation -> asset_fund_fee_pool_operation

The others are virtual operations so the fees are zero.

Related code is [here](https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/include/graphene/chain/protocol/fee_schedule.hpp#L65-L108)
