### ISSUE TITLE
[4] BSIP30: Always allow increasing the ratio of margin positions

### ISSUE THREAD

**Issue by HarukaMa** [bitshares/bitshares-ui#1577]
**Is your feature request related to a problem? Please describe.**
[BSIP30](https://github.com/bitshares/bsips/blob/master/bsip-0030.md) allows the users to increase the ratios of their short positions even if the ratio is still below the MCR. UI should allow that too after the hardfork.

**Describe the solution you'd like**
If the position is being called and the ratio is being increased when updating the position, **only if the debt is not being increased,** the update should always be allowed even if the new ratio is still below the MCR.

**Additional context**
ref: #1493 - creating separate feature requests for new needed UI features.

**Comment by startailcoon** [comment]
Bitshares-core is due for hardfork on 2018-07-19 14:00:00 UTC, this should be prioritized.

**Comment by startailcoon** [comment]
I hope that I understand this correctly, please review the following.

Today we have a Call Price even on bitUSD, involving a bunch of users. One of these are `gamma-rabit`, which I'll use as an example here.

## Exchange View
Here we can see that this user has a larger position for sale. It's the users entire debt. 

![bild](https://user-images.githubusercontent.com/12114550/41904896-e1d918b2-7939-11e8-99e4-f247e1b35659.png)

## Margin/Borrow view
On the margin/borrow view we can adjust this posisiton as usual. But so far you always had to go abow the 1.75 ratio (or the set MCR) for the asset.

From the next hard-fork, this will change so that you can update this position to any ratio larger than previous, yet smaller than the 1.75 ratio, but only if your position is in a margin call.

## Tasks
- [ ] When users asset is in margin call, allow the ratio to be changed.
- [ ] Lock the `Debt` value as only the collateral can be changed.
- [ ] Include details about the reason for this, only when the case is in affect.

**Comment by startailcoon** [comment]
## End Result

Note, this function will not work until the next core is released fully, which would correspond nicely with when the next Release Candidate goes into action.


![bitshares-margincalled](https://user-images.githubusercontent.com/12114550/41916442-57087cb8-7958-11e8-8451-06ee46fe5d25.gif)

**Comment by abitmore** [comment]
Need to be able to reduce debt, so don't lock it.

**Comment by startailcoon** [comment]
Right, good catch.

**Comment by startailcoon** [comment]
Debt can be changed as long as ratio isn't decreased.

Changed the message slightly

![bild](https://user-images.githubusercontent.com/12114550/41933962-a886a88a-7985-11e8-8e09-ab21598ba0ee.png)

**Comment by abitmore** [comment]
... as long as **ratio is increased** and **debt isn't increased**.

**Comment by startailcoon** [comment]
@abitmore lets see if I got it right this time then :)

![bild](https://user-images.githubusercontent.com/12114550/41940876-867afb82-799a-11e8-9b3c-90ccb731a434.png)

![bild](https://user-images.githubusercontent.com/12114550/41940889-8fc73836-799a-11e8-884e-d6498427c946.png)

**Comment by abitmore** [comment]
@startailcoon I'm not sure if it's correct.

Logic in bitshares-core:
* after adjusted a position, if it's not closed
  * if it got totally filled immediately (which means new rate < MCR, and there was sufficient depth on the book)
    * pass
  * else if new rate > MCR
    * pass
  * else if new rate > old rate
    * if new debt > old debt
      * error
    * else
      * pass
  * else
    * error

**Comment by startailcoon** [comment]
@abitmore hmm, ok. Lets go over it

## Previously
Possible to update any margin position
- If new rate < MCR
  - error
- Else
  - pass

## Current change
Possible to update any margin position
- If debt below MCR
  - If new rate < old rate
    - error
  - If new debt > old debt
    - error
  - Else
    - pass
- Else
  - If new rate > MCR
    - pass

The only question may be the `if it got totally filled immediately (which means new rate < MCR, and there was sufficient depth on the book)`. This was the case even before if I understood the BSIP correctly, but was never possible within the UI as it always required `new rate < MCR`. 

The update handles everything EXCEPT this, but I will need some help to find a good way to figure out if a new position will be able to be called in full. That would require a call/check on every single update of the position.

**Comment by abitmore** [comment]
> ## Current change
>Possible to update any margin position
>- If debt below MCR
>   - If new rate < old rate
>     - error
>   - If new debt > old debt
>     - error
>   - Else
>     - pass
>- Else
>   - If new rate > MCR
>     - pass

If ignore the immediate filling mechanism, the logic shoud be:

Possible to update any margin position
- If <del>debt below</del> **new rate <=** MCR
  - If new rate <del><</del>**<=** old rate
    - error
  - If new debt > old debt
    - error
  - Else
    - pass
- Else
<del>  - If new rate > MCR</del>
    - pass

**Comment by startailcoon** [comment]
I think I have this now

- If position is in margin call (what I ment with `If debt below MCR`)
  - If new rate <= MCR
    - If new rate <= old rate
      - error
    - If new debt > old debt
      - error
    - Else
      - pass
- Else if new rate > MCR
  - pass

**Comment by startailcoon** [comment]
Now, lets try this again then.

I've removed the disabled button on error, because this means an order can be set to a ratio where it can be margin called directly, if the user knows what he does. If the core doesn't like the operation it will fail in any case. We still display error messages, notifying the user about the possible issue with the new ratio.

The current math is as follows, which is a little changed from the original abow

- If position is in margin call
  - If new rate <= old rate 
    - show error `can't be below old rate on margin call`
  - else if new debt > old debt 
    - show error `can't increase debt on margin call`
- else
  - if new rate < MCR
    - show error `below MCR`
  - else if new rate < MCR + 0.5
    - show error `near MCR`



# Preview
As mentioned, button is always presnet and working. If the core doesn't like the requested operation we still receive an error. These errors can later be translated to a more user friendly statement instead.

Discussion about this can be posted in issue #1285, don't just disable buttons. 

![bitshares-margincalled_2](https://user-images.githubusercontent.com/12114550/42030292-9b9c04dc-7ad2-11e8-97b5-9e8f6567e487.gif)

### Trying to update below MCR today will result in the following core error
![bild](https://user-images.githubusercontent.com/12114550/42030615-acc12d0e-7ad3-11e8-8912-cc33cecd684c.png)

**Comment by abitmore** [comment]
- If **new** position is in margin call **// which means new rate <= MCR**
  - If new rate <= old rate
    - show error `can't be below old rate on margin call`
  - else if new debt > old debt 
    - show error `can't increase debt on margin call`
  - **else**
    - **show error `below MCR`**
- else
  <del>- if new rate < MCR</del>
    <del>- show error `below MCR`</del>
  - <del>else</del> if new rate < MCR + 0.5
    - show error `near MCR`

**Comment by startailcoon** [comment]
Yeah, well. That works to 👍

**Comment by startailcoon** [comment]
Well, that wouldn't work as 

`position is in margin call` != `new rate <= MCR`
`position is in margin call` == `original position is in margin call`

One is taken from what the original position is currently at, and the other what the user sets it to in the form.

Only original positions that is already in margin call are allowed to update the new rate to a value below the MCR.

This doesn't make sense to me, as if an original position is in margin call, they can be below MCR.
```
else
    show error below MCR
```

I think you're complicating things now :)

**Comment by startailcoon** [comment]
Another update as a margin call order would not show a `near MCR` error.

**NOW** I belive this should be done.
