### ISSUE TITLE
Implementing Elastic Search

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#1733]
This is a placeholder issue for tracking implementation of Elastic Search to the UI. 

By the end of the current Worker Priod (2019-03-01) we should try to complete integrating as much ES features as possible.

### Why ES
Elastic search is a highly dynamic and less resource required searchable database for various data on the chain. Instead of relying on nodes, that can change various parameters at will, we should query Elastic Search servers instead.

### Tasks
- [ ] Search History by TX ID (https://github.com/bitshares/bitshares-ui/issues/354)
- [ ] Show all History for Users (https://github.com/bitshares/bitshares-ui/issues/68, https://github.com/bitshares/bitshares-ui/issues/44, https://github.com/bitshares/bitshares-ui/issues/1665, https://github.com/bitshares/bitshares-ui/issues/1468)
- [ ] Signup Referrals (https://github.com/bitshares/bitshares-ui/issues/661)
