### ISSUE TITLE
Improving Gateway/Bridge Documentation and Codebase

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#1771]
The current system used for gateway/bridge access and communication is now a few years old and was introduced with the addition of Openledger.

The lack of documentation and knowledge of the workings of this has greatly limited the introduction of new gateways to the platform. Some work has been made to enhance the quality, but it still lacks some documents and has some confusing questions.

As a start, we should continue to improve the documentation, and perfect the current codebase.

# Major Tasks
- [ ] Enhance codebase (~10-15 hours) - https://github.com/bitshares/bitshares-ui/issues/2010
- [ ] Finish documentation of the Gateway and Bridge functions (~5 hours) - https://github.com/bitshares/bitshares-ui/issues/2011
- [ ] Swagger documentation (~5 hours) - https://github.com/bitshares/bitshares-ui/issues/2011

# Larger Tasks
- [ ] Removal of Legacy Gateway/Bridge - https://github.com/bitshares/bitshares-ui/issues/2249
- [ ]  Streamline updateGatewayBackers usage - #2484
 
# Minor Tasks
- [ ] Handle long reponses for external address queries - #1428 
- [ ] Exchange Gateway Deposit Replacement - #2144 
- [ ] Warning text when you click Deposit/Withdraw for the first time - #821 
- [ ] Add 'State of the Gateways' feed in News section - #2445 
- [ ] Integration Testing - Quick Deposit Button Missing - #2180
- [x] Withdraw Modal Enhancements #2522 
- [x] Legacy Despot/Withdraw Issues - https://github.com/bitshares/bitshares-ui/issues/2325
- [x] Gateway Modal ANT Implementation - https://github.com/bitshares/bitshares-ui/issues/1872
- [x] New Deposit / Withdraw modal u/s - #2446 
- [x] Deposit operation - inoperable - #2469 
- [x] Portfolio Deposit/Witdhraw/Buy Icons doesn't render on logged out Cloud Accounts - #2487 

# Sub-Tasks
- [x] New Gateway API Drafting - #2477

### Update 2018-10-02
Walking through the code of the Gateway/Bridge system, a number of difficulties where found and the code is a jumble. There are a number of enhancements that can be made to improve this system. Some was made as part of #1872 . The hours have been updated to ~20-25 hours for this.

### Update 2019-02-14
Task raised to Epic to track all issues related to Deposits and Withdrawls on Gateways and Bridges

**Comment by clockworkgr** [comment]
Can we get someone from OL to comment on what all the fields are? Anyone who worked on the UI side from back then who can comment on what they're used for/what's implemented?

**Comment by startailcoon** [comment]
I have a pretty good understanding of the system that we have today from when I enhanced it for the current unified config system. I know where to look in the code and have an overall picture of it.

Anyone that has an understanding of the system is free to help.
