### ISSUE TITLE
[1.5][gibbsfromncis][X][sschiessl-bcp][Showcases] General frame

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#1857]
<h1>Showing the strengths of the blockchain</h1>
It happens quite often in telegram channel that people look for approaches how to solve their task, and quite often it happens that the existing features can already help to realize it. The reference UI should show the strength of the blockchain, and currently it mostly leverages the exchange. The showcases intend to open new possibilities.

<h2>General frame</h2>
The showcases should be prominently included and the proposition is to have it as one of the main headers in the UI (title and icon to be discussed).

This issue is for discussion and for the implementation of a panel component that contains abstract tile components that will be used to display the differnt showcases in a grid view. Every showcase would have its own child of the tile component that allows to easily include it in the grid view. 

<h3>Tasks</h3>

- [x] Decide on a Icon and Title for the menu item
- [x] Create an mockup for the panel and abstract tile 
- [x] Implement an abstract tile component that allows for easy child components to faciliate adding new features
- [x] Implement the panel component that renders and presents the tiles
- [ ] Include the new panel next to the exchange in the menu

I will create a mockup the coming days to exemplify what I mean. This is meant as a feature proposal and can be rejected.

Posible tiles to be included
 - #1858 
 - #1859 
 - #1860 
 - More to come

I have assigned myself to all the issues since I possibly want to do the implemetation parts myself, and most of it all finish discussing them before anyone jumps on it.

**Comment by abitmore** [comment]
IMHO we need a showcase for proposals.

**Comment by sschiessl-bcp** [comment]
> IMHO we need showcases for proposals. Related issues: #1285 #1536 #1132 #866 #62 #1858

Thanks abit! I should have done a better research for past issues

**Comment by startailcoon** [comment]
If I understand this issue correctly You're talking about making sort of a FAQ/How-to section, containing answers on tasks that user may find useful. The chain is, as you state, a powerful tool and many thing may not be known by the user.

I think this would be a nice addition to the app as long as we can find a good way to implement it and have it easily accessible on the sections the user may need them.

**Comment by sschiessl-bcp** [comment]
Not only FAQ, actually providing easy to use UI for it!

**Comment by startailcoon** [comment]
After discussing this with @sschiessl-bcp , I've come to understand the goal a bit better. The usage of the word "Showcase" gave me the impression of it being a HowTo/FAQ section that visualized how users can use the app, which in itself isn't a bad idea either, but that wasn't the idea here.

@sschiessl-bcp wish to implement more of the "on-chain-ops" that we have. Like timed and recurring payments, escrow transfers etc. I would call these "Chain Features", but it's debatable. All these operations could possibly fit in their own section, but we can discuss that as well.

All these are new features, and advanced on chain features, some aren't ready in the core if I understand it. Lets discuss further and see what we can have coming here. Really looking forward to see these features in the UI.

**Comment by sschiessl-bcp** [comment]
> some aren't ready in the core if I understand it

The cases that have been already created are all possible already, merely require several operation and/or a Proposal Builder.

I ll try to give a more comprehensive update next week

**Comment by sschiessl-bcp** [comment]
This is a very basic and bad mockup, but it allows me to talk about the idea more (done with touchpad of laptop.. apologies):
![grafik](https://user-images.githubusercontent.com/33128181/45931689-c14c1a80-bf71-11e8-87da-3a7fc6d2f09c.png)

The UX is clear: Display parent component that holds a list of tiles that get displayed somehow. For the actual styling I imagine a separate issue after the basic framework is completed. This is due to two points:
 - the desired visualization (as tiles) might change as we progress (it will still be one parent displying a list)
 - one tile will be fully modularized and abstract. The component will merely receive a link, title, description and an icon. Adjusting the style afterwards will be easily done

What are your thoughts? I"d really like to push this.

**Comment by wmbutler** [comment]
I think `Showcase` is a great term (rather than features). We should probably put it into the menu since it's not something our regular users need to see constantly. Obviously, we can link directly to the endpoint from other sites who wish to discuss the various showcases.

**Comment by startailcoon** [comment]
> I think Showcase is a great term (rather than features).

Watching these now, I agree.

**Comment by sschiessl-bcp** [comment]
Here is a preview of the icon I made for it
![showcases svg](https://user-images.githubusercontent.com/33128181/47493376-672fc500-d84f-11e8-9d5f-1238dd73529d.png)

**Comment by sschiessl-bcp** [comment]
Here is a preview (styling still necessary)
![image](https://user-images.githubusercontent.com/33128181/49023026-90b57680-f196-11e8-980d-6ef7943c59c2.png)

**Comment by sschiessl-bcp** [comment]
I've asked @gibbsfromncis for styling this. I'd like elevated button look and feel of the tiles, with onhover and onclick effect. Additionally, the tiles should rearrange themselves when window is resized, max. 3 tiles in one row though (if possible).

**Comment by Agorise** [comment]
I love this! :) 
 
Can we make Invoicing easier? Business owners will love it. Tie it into the "Propose" feature too somehow. 
 
Paying invoices of course, ie: "Bill Pay". 
 
Timed transfers, recurring and scheduled payments of course, I totally agree we should have a card for that too. 
 
Maybe a "Get a Loan" card. 
 
"Manage Contracts" (create read update delete) 
For example, buy or sell a home, car, land or other physical property. The invoice gets tied to the property Title and the pdf document hash is stored with the transaction in the memo and the pdf itself can be accessed with c-ipfs (John @jmjatlanta and Jose @marcialvieira have all the code for this on [our github](https://github.com/Agorise?tab=repositories)).

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp 
<img width="1680" alt="screenshot 2018-11-30 08 20 54" src="https://user-images.githubusercontent.com/35899973/49274525-f21c6480-f478-11e8-9dcf-6597a23f4324.png">
<img width="1680" alt="screenshot 2018-11-30 08 20 38" src="https://user-images.githubusercontent.com/35899973/49274526-f2b4fb00-f478-11e8-90bc-af0d447bb2b0.png">
<img width="1680" alt="screenshot 2018-11-30 08 20 20" src="https://user-images.githubusercontent.com/35899973/49274527-f2b4fb00-f478-11e8-8bdd-cfbed3493e48.png">

**Comment by sschiessl-bcp** [comment]
https://develop.bitshares.org/#/spotlight

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp did you forgot to put your hours or it is OK?

**Comment by sschiessl-bcp** [comment]
Was in the PR, 6 hours

**Comment by startailcoon** [comment]
>           Was in the PR, 6 hours

Sorry, missed checking your PR comments for it.
Great work 👍

**Comment by bitfanatic** [comment]
> I love this! :)
> 
> Can we make Invoicing easier? Business owners will love it. Tie it into the "Propose" feature too somehow.
> 
> Paying invoices of course, ie: "Bill Pay".
> 
> Timed transfers, recurring and scheduled payments of course, I totally agree we should have a card for that too.
> 
> Maybe a "Get a Loan" card.
> 
> "Manage Contracts" (create read update delete)
> For example, buy or sell a home, car, land or other physical property. The invoice gets tied to the property Title and the pdf document hash is stored with the transaction in the memo and the pdf itself can be accessed with c-ipfs (John @jmjatlanta and Jose @marcialvieira have all the code for this on [our github](https://github.com/Agorise?tab=repositories)).

Could we integrate http://everprove.com/main into this for contracts 

And Basically let any company have this and integrate with bitshares 
That would be powerful stuff

A company would be able to run a large part of its business via bitshares and be very secure and save a ton of money in the process 

Just brain storming :)

**Comment by gibbsfromncis** [comment]
@bitfanatic If you want to see this kind of feature I need ask you the following questions to understand why and who will need it:
- What is the main feature of  [ http://everprove.com/](http://everprove.com/)?
- How integration of Bitshares and Ever Prove will work? Can you describe how do you see it in details?
- What are the group of users  need it? 
- What kind of problem ever prove help users to solve?

**Comment by bitfanatic** [comment]
> @bitfanatic If you want to see this kind of feature I need ask you the following questions to understand why and who will need it:
> 
> * What is the main feature of  [ http://everprove.com/](http://everprove.com/)?
> * How integration of Bitshares and Ever Prove will work? Can you describe how do you see it in details?
> * What are the group of users  need it?
> * What kind of problem ever prove help users to solve?

Yes off course 
Give me a little time to get it onto paper its pretty big ideas

And im not sure if bitshares can handle all off it

Because i have no experience in coding other than playing with swift coding on ipad

**Comment by gibbsfromncis** [comment]
@bitfanatic Unfortunately only small percentage of users are familiar with github and ready to share their ideas or post bugs there. We appreciate and open for any ideas, comments and objections. 

I personally would be glad to hear your big ideas and discuss it 👍
