### ISSUE TITLE
[10][dot5enko] Margin Position Updates

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#2127]
The UI Margin Position code is overdue for a refactoring to simplify the underlying code.

- [ ] Refactor app/components/Account/MarginPositions.jsx 

## Related tasks are 
- [ ] #2007 - No update on available DEBT asset
- [ ] #2004 - Redesign & Antify Borrow Modal
- [ ] #2005 - No working COLLATERAL lock

**Comment by startailcoon** [comment]
@dot5enko I'm assigning all three issues to you. I feel 2007 and 2004 touches the same concept, so I have only added hours to one of them. If you feel you need any clarification of these two issues, please post them in respective issue thread. 👍

**Comment by startailcoon** [comment]
I've added #2005 - `No working COLLATERAL lock` to the list of related tasks. This adresses an issue, that may or may not be solved as part of the other two.

**Comment by dot5enko** [comment]
ok

**Comment by froooze** [comment]
@dot5enko: I wrote a lot on the margin picker topics, can you integrate my ideas? What do you think ?

**Comment by dot5enko** [comment]
@froooze of course i'll look at them

**Comment by dot5enko** [comment]
@startailcoon i've refactored the code and fixed #1098 alongside. Frankly speaking the code was terrible and i exceeded estimate a bit:)  including #1098 it took around 11h. if its possible can you add the rest?
Also, related tasks were not accepted for integration by @wmbutler yet ( see #2004 )

**Comment by startailcoon** [comment]
Nice work @dot5enko 
Wasn't unexpected that this would take a bit longer than estimated. I'll push this to 10 hours + the 1 hour on #1098.
