### ISSUE TITLE
[2.0.181121-rc1] Integration tests

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2172]
<h1>Looking for Integration testers</h1>

This issue is to track integration tests of the mentioned release candidate. Targets are the most popular platforms
 - Mac
 - Windows 7 / 10
 - Linux
 - Android
 - iOS

and for each for the most popular browsers
 - Chrome
 - Firefox
 - Opera
 - Edge
 - Standard Android / iOS browser

Please indicate which of those you are able to test, expectancy is 0.5 hours per platform / browser. Reports are mandatory and must be done for every browser and platform. If you are interested in doing integration tests please do the following:

1. Copy the below report, choose your OS and browser and add it as a comment
2. Wait to be approved by the UI team 
3. Tick the checkboxes in your comment while doing the integration test

If you find any problems in rendering, error messages or simply weird behavior in the functionality listed in this issue, please report them as a [separate in github](https://github.com/bitshares/bitshares-ui/issues) and add a link as comment in here. Every issue must include a way how to reproduce them, what the error (please get familiar with how to obtain browser console logs) is and what an expected solution is. Reported issues that are accepted by the UI team will be added as bonus 0.1 hours for your payout.

<h1>Reporting</h1>
Copy everything in the box in your comment as template for the report, only one browser / OS per report

```
My OS:
  - Mac/Windows/Linux/Android/iOS, Version: <version>

My Browser:
 - Chrome/Firefox/Opera/Edge/etc., Version: <version>

General 
 - [ ] Wallet loads and connects
 - [ ] Login via cloud login and local wallet
 - [ ] Transfer between accounts
 - [ ] Exchange opens, orders are visible and limit orders can be put
 - [ ] Margin creation and adjustment is possible
 - [ ] Voting is possible (committee, witness, proposals)

Specific components:
 - [ ] #422 Added Price Alerts for Exchange
    - Put an alert above and below current market prive of e.g. BTS/CNY or BTS/USD. Wait until the alert triggers and if it displays properly
 - [ ] #1724 Private login feature for Cloud Login
    - Login while having "Remember Me" disabled. Close the wallet in some way and reopen it. No account information may be retained
 - [ ] #1696 Add easier way to create a report for debugging
    - Click on "Report" in the lower right bottom. Does the Screenshot and log files present properly? Create a new github issue and do a dummy report, just to try the functionality. Link the link to new issue here
 - [ ] #2130 Multiple quick deposit buttons/ borrow buttons- as well as inactive tooltips
    - Test https://staging.bitshares.org/#/market/BTS_OPEN.ETH the "Depost ETH" buttons in the exchange. Are all hints showing properly? Are there two options to "Deposit ETH"?
 - [ ] #2110 'My open orders' contains mixed pairs orders in latest release
```

<h1>Participants</h1>

 - Windows/Edge: @bieglich (failed, reward 0.1) @toi16 (failed, reward 0.1)
 - Windows/Firefox: @bieglich (done) @toi16 (done)
 - Windows/Chrome: @bieglich (done) @toi16 (done)
 - Windows/Opera: @TechsUsInc (done)
 - Mac/Chrome: @thehapax (done)
 - Mac/Safari: @thehapax (done)
 - Android/Chrome @bieglich (done)

<h1>Accepted Issues</h1>
 - @toi16  #2173 #2174 #2175 #2176 #2177 #2179 #2180 #2181
 - @thehapax #2194
 - @TechsUsInc #2202 #2203 #2204
 - @bieglich #2215 #2214

<h1>Payout</h1>

 - @toi16 2
 - @thehapax 1.1
 - @TechsUsInc 0.8
 - @bieglich 1.8
 - @sschiessl-bcp 2

**Comment by bieglich** [comment]
I'd be interested in doing Windows 10 (Chrome and Firefox) and Android (Chrome)

**Comment by thehapax** [comment]
My OS:
  - Mac/iOS, Version: 10.13

My Browser:
 - Chrome/Safari/Brave Version: 70.0.3538.77 / 12.0.1/ 0.25.2

General 
 - [ ] Wallet loads and connects
 - [ ] Login via cloud login and local wallet
 - [ ] Transfer between accounts
 - [ ] Exchange opens, orders are visible and limit orders can be put
 - [ ] Margin creation and adjustment is possible
 - [ ] Voting is possible (committee, witness, proposals)

Specific components:
 - [ ] #422 Added Price Alerts for Exchange
    - Put an alert above and below current market prive of e.g. BTS/CNY or BTS/USD. Wait until the alert triggers and if it displays properly
 - [ ] #1724 Private login feature for Cloud Login
    - Login while having "Remember Me" disabled. Close the wallet in some way and reopen it. No account information may be retained
 - [ ] #1696 Add easier way to create a report for debugging
    - Click on "Report" in the lower right bottom. Does the Screenshot and log files present properly? Create a new github issue and do a dummy report, just to try the functionality. Link the link to new issue here
 - [ ] #2130 Multiple quick deposit buttons/ borrow buttons- as well as inactive tooltips
    - Test https://wallet.bitshares.org/#/market/BTS_OPEN.ETH the "Depost ETH" buttons in the exchange. Are all hints showing properly? Are there two options to "Deposit ETH"?
 - [ ] #2110 'My open orders' contains mixed pairs orders in latest release

**Comment by thehapax** [comment]
My OS:
  - Mac Version: 10.13.6

My Browser:
 - Safari Version:  12.0.1

General 
 - [ ] Wallet loads and connects
 - [ ] Login via cloud login and local wallet
 - [ ] Transfer between accounts
 - [ ] Exchange opens, orders are visible and limit orders can be put
 - [ ] Margin creation and adjustment is possible
 - [ ] Voting is possible (committee, witness, proposals)

Specific components:
 - [ ] #422 Added Price Alerts for Exchange
    - Put an alert above and below current market prive of e.g. BTS/CNY or BTS/USD. Wait until the alert triggers and if it displays properly
 - [ ] #1724 Private login feature for Cloud Login
    - Login while having "Remember Me" disabled. Close the wallet in some way and reopen it. No account information may be retained
 - [ ] #1696 Add easier way to create a report for debugging
    - Click on "Report" in the lower right bottom. Does the Screenshot and log files present properly? Create a new github issue and do a dummy report, just to try the functionality. Link the link to new issue here
 - [ ] #2130 Multiple quick deposit buttons/ borrow buttons- as well as inactive tooltips
    - Test https://wallet.bitshares.org/#/market/BTS_OPEN.ETH the "Depost ETH" buttons in the exchange. Are all hints showing properly? Are there two options to "Deposit ETH"?
 - [ ] #2110 'My open orders' contains mixed pairs orders in latest release

**Comment by sschiessl-bcp** [comment]
@thehapax go ahead on both

@bieglich please create a comment like shown above for each pair you want to test

**Comment by toi16** [comment]
My OS:
  - Windows 10, Version: 1803 (OS Build 17134.407)

My Browser:
 - Chrome Version: 70.0.3538.102 (Official Build) (64-bit)

General 
 - [ ] Wallet loads and connects
 - [ ] Login via cloud login and local wallet
 - [ ] Transfer between accounts
 - [ ] Exchange opens, orders are visible and limit orders can be put
 - [ ] Margin creation and adjustment is possible
 - [ ] Voting is possible (committee, witness, proposals)

Specific components:
 - [ ] #422 Added Price Alerts for Exchange
    - Put an alert above and below current market prive of e.g. BTS/CNY or BTS/USD. Wait until the alert triggers and if it displays properly
 - [ ] #1724 Private login feature for Cloud Login
    - Login while having "Remember Me" disabled. Close the wallet in some way and reopen it. No account information may be retained
 - [ ] #1696 Add easier way to create a report for debugging
    - Click on "Report" in the lower right bottom. Does the Screenshot and log files present properly? Create a new github issue and do a dummy report, just to try the functionality. Link the link to new issue here
 - [ ] #2130 Multiple quick deposit buttons/ borrow buttons- as well as inactive tooltips
    - Test https://wallet.bitshares.org/#/market/BTS_OPEN.ETH the "Depost ETH" buttons in the exchange. Are all hints showing properly? Are there two options to "Deposit ETH"?
 - [ ] #2110 'My open orders' contains mixed pairs orders in latest release

**Comment by toi16** [comment]
My OS:
  - Windows 10, Version: 1803 (OS Build 17134.407)

My Browser:
 - Microsoft Edge 42.17134.1.0

General 
 - [ ] Wallet loads and connects
 - [ ] Login via cloud login and local wallet
 - [ ] Transfer between accounts
 - [ ] Exchange opens, orders are visible and limit orders can be put
 - [ ] Margin creation and adjustment is possible
 - [ ] Voting is possible (committee, witness, proposals)

Specific components:
 - [ ] #422 Added Price Alerts for Exchange
    - Put an alert above and below current market prive of e.g. BTS/CNY or BTS/USD. Wait until the alert triggers and if it displays properly
 - [ ] #1724 Private login feature for Cloud Login
    - Login while having "Remember Me" disabled. Close the wallet in some way and reopen it. No account information may be retained
 - [ ] #1696 Add easier way to create a report for debugging
    - Click on "Report" in the lower right bottom. Does the Screenshot and log files present properly? Create a new github issue and do a dummy report, just to try the functionality. Link the link to new issue here
 - [ ] #2130 Multiple quick deposit buttons/ borrow buttons- as well as inactive tooltips
    - Test https://wallet.bitshares.org/#/market/BTS_OPEN.ETH the "Depost ETH" buttons in the exchange. Are all hints showing properly? Are there two options to "Deposit ETH"?
 - [ ] #2110 'My open orders' contains mixed pairs orders in latest release

**Comment by toi16** [comment]
My OS:
  - Windows 10, Version: 1803 (OS Build 17134.407)

My Browser:
 - Firefox Version: 63.0.3 (64-bit)

General 
 - [ ] Wallet loads and connects
 - [ ] Login via cloud login and local wallet
 - [ ] Transfer between accounts
 - [ ] Exchange opens, orders are visible and limit orders can be put
 - [ ] Margin creation and adjustment is possible
 - [ ] Voting is possible (committee, witness, proposals)

Specific components:
 - [ ] #422 Added Price Alerts for Exchange
    - Put an alert above and below current market prive of e.g. BTS/CNY or BTS/USD. Wait until the alert triggers and if it displays properly
 - [ ] #1724 Private login feature for Cloud Login
    - Login while having "Remember Me" disabled. Close the wallet in some way and reopen it. No account information may be retained
 - [ ] #1696 Add easier way to create a report for debugging
    - Click on "Report" in the lower right bottom. Does the Screenshot and log files present properly? Create a new github issue and do a dummy report, just to try the functionality. Link the link to new issue here
 - [ ] #2130 Multiple quick deposit buttons/ borrow buttons- as well as inactive tooltips
    - Test https://wallet.bitshares.org/#/market/BTS_OPEN.ETH the "Depost ETH" buttons in the exchange. Are all hints showing properly? Are there two options to "Deposit ETH"?
 - [ ] #2110 'My open orders' contains mixed pairs orders in latest release

**Comment by Bluffet** [comment]
Is this a joke? I can't get to the log in.

Mac OS 10.9.5 / Firefox 

Chrome gets there.

**Comment by sschiessl-bcp** [comment]
@toi16 Please go ahead with all three

**Comment by bieglich** [comment]
My OS:
  - Windows 10

My Browser:
 - Chrome

General 
 - [ ] Wallet loads and connects
 - [ ] Login via cloud login and local wallet
 - [ ] Transfer between accounts
 - [ ] Exchange opens, orders are visible and limit orders can be put
 - [ ] Margin creation and adjustment is possible
 - [ ] Voting is possible (committee, witness, proposals)

Specific components:
 - [ ] #422 Added Price Alerts for Exchange
    - Put an alert above and below current market prive of e.g. BTS/CNY or BTS/USD. Wait until the alert triggers and if it displays properly
 - [ ] #1724 Private login feature for Cloud Login
    - Login while having "Remember Me" disabled. Close the wallet in some way and reopen it. No account information may be retained
 - [ ] #1696 Add easier way to create a report for debugging
    - Click on "Report" in the lower right bottom. Does the Screenshot and log files present properly? Create a new github issue and do a dummy report, just to try the functionality. Link the link to new issue here
 - [ ] #2130 Multiple quick deposit buttons/ borrow buttons- as well as inactive tooltips
    - Test https://wallet.bitshares.org/#/market/BTS_OPEN.ETH the "Depost ETH" buttons in the exchange. Are all hints showing properly? Are there two options to "Deposit ETH"?
 - [ ] #2110 'My open orders' contains mixed pairs orders in latest release

**Comment by bieglich** [comment]
My OS:
  - Windows 10

My Browser:
 - Firefox

General 
 - [ ] Wallet loads and connects
 - [ ] Login via cloud login and local wallet
 - [ ] Transfer between accounts
 - [ ] Exchange opens, orders are visible and limit orders can be put
 - [ ] Margin creation and adjustment is possible
 - [ ] Voting is possible (committee, witness, proposals)

Specific components:
 - [ ] #422 Added Price Alerts for Exchange
    - Put an alert above and below current market prive of e.g. BTS/CNY or BTS/USD. Wait until the alert triggers and if it displays properly
 - [ ] #1724 Private login feature for Cloud Login
    - Login while having "Remember Me" disabled. Close the wallet in some way and reopen it. No account information may be retained
 - [ ] #1696 Add easier way to create a report for debugging
    - Click on "Report" in the lower right bottom. Does the Screenshot and log files present properly? Create a new github issue and do a dummy report, just to try the functionality. Link the link to new issue here
 - [ ] #2130 Multiple quick deposit buttons/ borrow buttons- as well as inactive tooltips
    - Test https://wallet.bitshares.org/#/market/BTS_OPEN.ETH the "Depost ETH" buttons in the exchange. Are all hints showing properly? Are there two options to "Deposit ETH"?
 - [ ] #2110 'My open orders' contains mixed pairs orders in latest release

**Comment by bieglich** [comment]
My OS:
  - Windows 10

My Browser:
 - Edge

General 
 - [ ] Wallet loads and connects
 - [ ] Login via cloud login and local wallet
 - [ ] Transfer between accounts
 - [ ] Exchange opens, orders are visible and limit orders can be put
 - [ ] Margin creation and adjustment is possible
 - [ ] Voting is possible (committee, witness, proposals)

Specific components:
 - [ ] #422 Added Price Alerts for Exchange
    - Put an alert above and below current market prive of e.g. BTS/CNY or BTS/USD. Wait until the alert triggers and if it displays properly
 - [ ] #1724 Private login feature for Cloud Login
    - Login while having "Remember Me" disabled. Close the wallet in some way and reopen it. No account information may be retained
 - [ ] #1696 Add easier way to create a report for debugging
    - Click on "Report" in the lower right bottom. Does the Screenshot and log files present properly? Create a new github issue and do a dummy report, just to try the functionality. Link the link to new issue here
 - [ ] #2130 Multiple quick deposit buttons/ borrow buttons- as well as inactive tooltips
    - Test https://wallet.bitshares.org/#/market/BTS_OPEN.ETH the "Depost ETH" buttons in the exchange. Are all hints showing properly? Are there two options to "Deposit ETH"?
 - [ ] #2110 'My open orders' contains mixed pairs orders in latest release

**Comment by bieglich** [comment]
My OS:
  - Android

My Browser:
 - Chrome

General 
 - [ ] Wallet loads and connects
 - [ ] Login via cloud login and local wallet
 - [ ] Transfer between accounts
 - [ ] Exchange opens, orders are visible and limit orders can be put
 - [ ] Margin creation and adjustment is possible
 - [ ] Voting is possible (committee, witness, proposals)

Specific components:
 - [ ] #422 Added Price Alerts for Exchange
    - Put an alert above and below current market prive of e.g. BTS/CNY or BTS/USD. Wait until the alert triggers and if it displays properly
 - [ ] #1724 Private login feature for Cloud Login
    - Login while having "Remember Me" disabled. Close the wallet in some way and reopen it. No account information may be retained
 - [ ] #1696 Add easier way to create a report for debugging
    - Click on "Report" in the lower right bottom. Does the Screenshot and log files present properly? Create a new github issue and do a dummy report, just to try the functionality. Link the link to new issue here
 - [ ] #2130 Multiple quick deposit buttons/ borrow buttons- as well as inactive tooltips
    - Test https://wallet.bitshares.org/#/market/BTS_OPEN.ETH the "Depost ETH" buttons in the exchange. Are all hints showing properly? Are there two options to "Deposit ETH"?
 - [ ] #2110 'My open orders' contains mixed pairs orders in latest release

**Comment by sschiessl-bcp** [comment]
@bieglich please fill out the details of version, then go ahead with all four

**Comment by Bluffet** [comment]
![image](https://user-images.githubusercontent.com/31476976/48616636-7ad4d400-e994-11e8-889e-5b7cf9e7f8b5.png)

Well, Mac OS 10.9.5 / firefox stopped at this point @sschiessl-bcp 

Coincides with a user report this morning.

**Comment by toi16** [comment]
Bug Logged: https://github.com/bitshares/bitshares-ui/issues/2173

**Comment by toi16** [comment]
Bug Logged: https://github.com/bitshares/bitshares-ui/issues/2174

**Comment by toi16** [comment]
Bug Logged: https://github.com/bitshares/bitshares-ui/issues/2175

**Comment by toi16** [comment]
Bug Logged: https://github.com/bitshares/bitshares-ui/issues/2176

**Comment by toi16** [comment]
Dummy Report Submitted for Win10/Chrome: https://github.com/bitshares/bitshares-ui/issues/2177

**Comment by toi16** [comment]
Bug #2176 updated with Firefox specific problem.

**Comment by toi16** [comment]
Bug Logged: https://github.com/bitshares/bitshares-ui/issues/2179

**Comment by toi16** [comment]
Bug Logged: https://github.com/bitshares/bitshares-ui/issues/2180

**Comment by toi16** [comment]
Bug Logged: https://github.com/bitshares/bitshares-ui/issues/2181

**Comment by toi16** [comment]
@sschiessl-bcp 
I have finished testing all three configurations as far as I can.
Please let me know if you would like anything else tested.

**Comment by sschiessl-bcp** [comment]
@TechsUsInc Please go ahead with Opera. For the other two browsers we have already testers. Could you also do something on mobile?

**Comment by sschiessl-bcp** [comment]
@thehapax @bieglich How is testing going?

**Comment by sschiessl-bcp** [comment]
> I'm unable to do mobile ATM but working on it. I can also test Brave browser.

@TechsUsInc Please stick to Opera for now

**Comment by thehapax** [comment]
> @thehapax @bieglich How is testing going?
@sschiessl-bcp  I started working on the first part.  give me a day, sorry things a little hectic here.

**Comment by thehapax** [comment]
Bug logged https://github.com/bitshares/bitshares-ui/issues/2194

**Comment by sschiessl-bcp** [comment]
@thehapax you have two points in the test above unchecked, does this mean still to be done, or it didnt work?

**Comment by TechsUsInc** [comment]
Bug logged #2202

**Comment by TechsUsInc** [comment]
bug logged #2203

**Comment by TechsUsInc** [comment]
Bug logged #2204

**Comment by bieglich** [comment]
Multiple buttons still not present with the actual release on Chrome (Windows and Android)

**Comment by thehapax** [comment]
> @thehapax you have two points in the test above unchecked, does this mean still to be done, or it didnt work?

@sschiessl-bcp I am now done

**Comment by bieglich** [comment]
Bug #2214 and #2215

**Comment by sschiessl-bcp** [comment]
This testing is completed. Please come back for the next release candidate! Any and all feedback is welcome (especially with respect to the estimates for testing).

My own: 2

@startailcoon @wmbutler 
My suggestion for the title: "[7.7 multiple][2.0.181121-rc1] Integration tests". The multiple in the head indicates that the payout distribution is stated in the first post of the issue.

**Comment by sschiessl-bcp** [comment]
@toi16 @thehapax @TechsUsInc @bieglich 
Please state your BitShares Account name for payout.

**Comment by bieglich** [comment]
Just the same: bieglich

**Comment by toi16** [comment]
My Bitshares account name is: toi16

**Comment by TechsUsInc** [comment]
@sschiessl-bcp 
lil-bi.t-of-techs-us

**Comment by startailcoon** [comment]
> My suggestion for the title: "[7.7 multiple][2.0.181121-rc1] Integration tests"

Sounds good to me. 👍

**Comment by thehapax** [comment]
@sschiessl-bcp octet1

**Comment by wmbutler** [comment]
Should I just split the payment between @toi16 @thehapax @TechsUsInc @bieglich equally?

**Comment by sschiessl-bcp** [comment]
The first post contains the distribution in the end, sorry about marking that not clearly
