### ISSUE TITLE
[8][multiple][2.0.181212-rc1] Integration tests

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2274]
<h1>Looking for Integration testers</h1>

This issue is to track integration tests of the mentioned release candidate. Targets are the most popular platforms
 - Mac
 - Windows 7 / 10
 - Linux
 - Android
 - iOS

and for each for the most popular browsers
 - Chrome
 - Firefox
 - Opera
 - Edge
 - Standard Android / iOS browser

Please indicate which of those you are able to test, expectancy is 0.5 hours per platform / browser. Reports are mandatory and must be done for every browser and platform. If you are interested in doing integration tests please do the following:

1. Choose your OS(s) and browser(s) and indicate with a comment that you are interested
2. Wait to be approved by the UI team, a new issue will be created by us for your testing
3. Copy the below template in the new issue that was created for you, for each OS/browser pair
3. Tick the checkboxes in your comment while doing the integration test for each OS/browser pair 

If you find any problems in rendering, error messages or simply weird behavior in the functionality listed in this issue, please report them as a [separate issue in github](https://github.com/bitshares/bitshares-ui/issues) and add a link as comment in the new issue that was created for you. Every issue must include a way how to reproduce them, what the error (please get familiar with how to obtain browser console logs) is and what an expected solution is. Reported issues that are accepted by the UI team will be added as bonus 0.1 hours for your payout.

<h1>Reporting</h1>
Copy everything in the box in your comment as template for the report, only one browser / OS per report

```
My OS:
  - Mac/Windows/Linux/Android/iOS, Version: <version>

My Browser:
 - Chrome/Firefox/Opera/Edge/etc., Version: <version>

General 
 - [ ] Wallet loads and connects
 - [ ] Login via cloud login and local wallet
 - [ ] Transfer between accounts
 - [ ] Exchange opens, orders are visible and limit orders can be put
 - [ ] Margin creation and adjustment is possible
 - [ ] Voting is possible (committee, witness, proposals)

Specific components:
 - [ ] #2221 Collateral Bidding
    - Find the collateral bid overview, test in small and big browser size. Try to add a bid (you may cancel before broadcasting), optionally add and remove a bid
 - [ ] #2023 Create a paper wallet, with and without private keys
 - [ ] #2127 View the margin position table in the dashboard, are all rows displayed properly and loaded correctly?
 - [ ] #2224 Attempt to settle any amount of bitUSD (settlement button in exchange and margin position table in dashboard). Does the modal open correctly? Are the values presented properly, and the price overview correct? Optionally, do actually settle any amount of bitUSD
```

<h1>Participants</h1>

- @TechsUsInc #2276
- @toi16 #2281
- @Kennybll #2334 
- @clockworkgr #2279

<h1>Found issues and payouts</h1>

- @TechsUsInc #2291 #2297 #2298 #2299 #2301 #2302  #2310 #2311 #2312 #2319 #2320 #2322 #2310 #2324 #2327 #2328 #2346 #2355 #2356 #2357 #2358 #2359 #2366 #2390 #2396; payout 4
- @toi16 #2282 #2283 #2284; payout 1.3
- @Kennybll #2335; payout 0.6
- @clockworkgr #2279; payout  0.1
- @sschiessl-bcp  payout 2

**Comment by TechsUsInc** [comment]
My OS:
  - Windows, Version: 8.1

My Browser:
 Opera 56.0.3051.116

General 
 - [ ] Wallet loads and connects
 - [ ] Login via cloud login and local wallet
 - [ ] Transfer between accounts
 - [ ] Exchange opens, orders are visible and limit orders can be put
 - [ ] Margin creation and adjustment is possible
 - [ ] Voting is possible (committee, witness, proposals)

Specific components:
 - [ ] #2221 Collateral Bidding
    - Find the collateral bid overview, test in small and big browser size. Try to add a bid (you may cancel before broadcasting), optionally add and remove a bid
 - [ ] #2023 Create a paper wallet, with and without private keys
 - [ ] #2127 View the margin position table in the dashboard, are all rows displayed properly and loaded correctly?
 - [ ] #2224 Attempt to settle any amount of bitUSD (settlement button in exchange and margin position table in dashboard). Does the modal open correctly? Are the values presented properly, and the price overview correct? Optionally, do actually settle any amount of bitUSD

**Comment by sschiessl-bcp** [comment]
@TechsUsInc Please go ahead with:
- Windows 8.1 / Opera
- Windows 8.1 / Chrome
- Windows 8.1 / Firefox

I assume for Chrome and Firefox you are also using latest version? For Linux, which distribution are you using? What do you mean with Android as Browser?

Please use this issue for your testing: https://github.com/bitshares/bitshares-ui/issues/2276
Copy the template for each pair in there as well, this should help with the overview

**Comment by toi16** [comment]
My OS:
Windows 10, Version: 1803 (OS Build 17134.407)

My Browser:
Chrome, Version 71.0.3578.80 (Official Build) (64-bit)
Firefox, Version: 63.0.3 (64-bit)
Edge, Version: Microsoft Edge 42.17134.1.0

**Comment by sschiessl-bcp** [comment]
@toi16 Please go ahead with

- Windows 10 / Chrome
- Windows 10 / Firefox

Edge will still not work, not necessary.

Please use this issue for your testing: #2281
Copy the template for each pair in there as well, this should help with the overview

**Comment by TechsUsInc** [comment]
> @TechsUsInc Please go ahead with:
> 
> * Windows 8.1 / Opera
> * Windows 8.1 / Chrome
> * Windows 8.1 / Firefox
> 
> I assume for Chrome and Firefox you are also using latest version? For Linux, which distribution are you using? What do you mean with Android as Browser?
> 
> Please use this issue for your testing: #2276
> Copy the template for each pair in there as well, this should help with the overview

Yes Sir. I updated the issue with versions/Distros requested.

**Comment by proteanx** [comment]
My OS:
Debian 9 (Stable 9.x)
Kali-Linux (Rolling-Release w/ Debian testing/unstable)

My Browsers (stable):
firefox-esr 60.4.0esr-1~deb9u1 amd64
chromium 71.0.3578.80-1~deb9u1 amd64

**Comment by Kennybll** [comment]
My OS:
Windows 10 Home 1803
Android 7.1.1 (Nougat)

My Browser:
Google Version 70.0.3538.110 (Official Build) (64-bit) - Windows 10
Microsoft Edge 42.17134.1.0 - Windows 10
Brave Browser 0.57.18 Chromium: 71.0.3578.80 (Official Build) (64-bit) - Windows 10
Google Chrome Version 70.0.3538.80 - Android 7.1.1 (Nougat)
FireFox Version 63.0.2 - Android 7.1.1 (Nougat)
Brave Browser 1.0.70 Chromium 70.0.3538.110 - Android 7.1.1 (Nougat)

**Comment by sschiessl-bcp** [comment]
@proteanx please go ahead with firefox on both OS

**Comment by sschiessl-bcp** [comment]
@kennybll go ahead with android and firefox/brave

**Comment by sschiessl-bcp** [comment]
Closed, thanks for all participants!

**Comment by wmbutler** [comment]
@toi16 please post your bts payment address.

**Comment by sschiessl-bcp** [comment]
Some are listed in payouts (bottom of first post) here
https://github.com/bitshares/bitshares-ui/issues/2274#issuecomment-453884839

**Comment by toi16** [comment]
Hi, my BTS address is : toi16

**Comment by matle85** [comment]
Windows 10

Chrome
Firefox
Edge

Android Samsung S9

Chrome
Samsung internet
Duckduckgo

**Comment by akledirs** [comment]
Ready for testing...
OS: Windows 10 1809 (17763.379)
Browsers: Latest ver. Edge, Chrome, Firefox
OS 2: Android 6.0
Browsers: Standard Android Browser; Latest ver. Chrome, Firefox

**Comment by Bluffet** [comment]
For shits and giggles, I gave iOS another go. This time with BRAVE browser.

To my surprise it did not just die straight away, it counted through the nodes in my area and presented me with the familiar login dialogue.

Logged in and anticipation builds up: this is so cool... until I tried to maneuver to the dashboard.... white screen of death... 

Close! But no cigar! And naturally I could not perform the test battery. Tried it both in wallet and staging with same result.

donations666

My OS:
  - iOS, Version: 12.2

My Browser:
 - Brave., Version: 1.9.1

General 
 - [ x] Wallet loads and connects
 - [ x] Login via cloud login 
 - [ ] Transfer between accounts
 - [ ] Exchange opens, orders are visible and limit orders can be put
 - [ ] Margin creation and adjustment is possible
 - [ ] Voting is possible (committee, witness, proposals)

Specific components:
 - [ ] #2221 Collateral Bidding
    - Find the collateral bid overview, test in small and big browser size. Try to add a bid (you may cancel before broadcasting), optionally add and remove a bid
 - [ ] #2023 Create a paper wallet, with and without private keys
 - [ ] #2127 View the margin position table in the dashboard, are all rows displayed properly and loaded correctly?
 - [ ] #2224 Attempt to settle any amount of bitUSD (settlement button in exchange and margin position table in dashboard). Does the modal open correctly? Are the values presented properly, and the price overview correct? Optionally, do actually settle any amount of bitUSD
