### ISSUE TITLE
[2.0.181212-rc1] Integration testing by TechsUsInc

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2276]
For easier overview https://github.com/bitshares/bitshares-ui/issues/2274

**Comment by TechsUsInc** [comment]
My OS:
Windows, Version: 8.1 (Primary)
 Windows, Version 10
Linux        Ubuntu Version 16.04
Linux        Ubuntu Version 18.04
Android 7.1.1 (Nougat) 

My Browser:
Opera 56.0.3051.116  (Primary)
Google Version 70.0.3538.110 (Official Build) (64-bit)
Firefox Version 63.0.3(64-bit)
Brave Version 0.25.2 V8 6.9.427.23 OS Release 6.3.9600  
Bitorrent Version 7.10.4.44847

General 
 - [ ] Wallet loads and connects
 - [ ] Login via cloud login and local wallet
 - [ ] Transfer between accounts
 - [ ] Exchange opens, orders are visible and limit orders can be put
 - [ ] Margin creation and adjustment is possible
 - [ ] Voting is possible (committee, witness, proposals)

Specific components:
 - [ ] #2221 Collateral Bidding
    - Find the collateral bid overview, test in small and big browser size. Try to add a bid (you may cancel before broadcasting), optionally add and remove a bid
 - [ ] #2023 Create a paper wallet, with and without private keys
 - [ ] #2127 View the margin position table in the dashboard, are all rows displayed properly and loaded correctly?
 - [ ] #2224 Attempt to settle any amount of bitUSD (settlement button in exchange and margin position table in dashboard). Does the modal open correctly? Are the values presented properly, and the price overview correct? Optionally, do actually settle any amount of bitUSD

**Comment by TechsUsInc** [comment]
My OS:
Windows, Version: 8.1 (Primary)

My Browser:
Google Version 70.0.3538.110 (Official Build) (64-bit)

General

  Wallet loads and connects
  Login via cloud login and local wallet
  Transfer between accounts
  Exchange opens, orders are visible and limit orders can be put
  Margin creation and adjustment is possible
  Voting is possible (committee, witness, proposals)
Specific components:

  #2221 Collateral Bidding
Find the collateral bid overview, test in small and big browser size. Try to add a bid (you may cancel before broadcasting), optionally add and remove a bid
  #2023 Create a paper wallet, with and without private keys
  #2127 View the margin position table in the dashboard, are all rows displayed properly and loaded correctly?
  #2224 Attempt to settle any amount of bitUSD (settlement button in exchange and margin position table in dashboard). Does the modal open correctly? Are the values presented properly, and the price overview correct? Optionally, do actually settle any amount of bitUSD

**Comment by TechsUsInc** [comment]
My OS:
Windows, Version: 8.1 (Primary)

My Browser:
Firefox Version 63.0.3(64-bit)

General

Wallet loads and connects
Login via cloud login and local wallet
Transfer between accounts
Exchange opens, orders are visible and limit orders can be put
Margin creation and adjustment is possible
Voting is possible (committee, witness, proposals)
Specific components:

#2221 Collateral Bidding
Find the collateral bid overview, test in small and big browser size. Try to add a bid (you may cancel before broadcasting), optionally add and remove a bid
#2023 Create a paper wallet, with and without private keys
#2127 View the margin position table in the dashboard, are all rows displayed properly and loaded correctly?
#2224 Attempt to settle any amount of bitUSD (settlement button in exchange and margin position table in dashboard). Does the modal open correctly? Are the values presented properly, and the price overview correct? Optionally, do actually settle any amount of bitUSD

**Comment by TechsUsInc** [comment]
Please see #2295

**Comment by TechsUsInc** [comment]
Please see #2297

**Comment by TechsUsInc** [comment]
Please see #2298

**Comment by TechsUsInc** [comment]
Please see #2299

**Comment by TechsUsInc** [comment]
Please see #2301

**Comment by TechsUsInc** [comment]
Please see #2302

**Comment by TechsUsInc** [comment]
Please see #2303

**Comment by TechsUsInc** [comment]
Please see #2311

**Comment by TechsUsInc** [comment]
Please see #2319

**Comment by TechsUsInc** [comment]
Please see #2320

**Comment by TechsUsInc** [comment]
Google testing complete. Experienced all of the same issues reported above. Mainly connection issue, white tradingview screen in exchange. Also, Paper wallets were both saved as PDF with Google unlike Opera.

**Comment by TechsUsInc** [comment]
Please see #2321 
Will not load with Firefox at all

**Comment by TechsUsInc** [comment]
Please see #2322

**Comment by TechsUsInc** [comment]
Please see #2323

**Comment by TechsUsInc** [comment]
Please see #2324

**Comment by TechsUsInc** [comment]
Please see #2327

**Comment by TechsUsInc** [comment]
Please see #2328

**Comment by TechsUsInc** [comment]
Please see #2329

**Comment by TechsUsInc** [comment]
Please see #2346

**Comment by TechsUsInc** [comment]
Please see #2355

**Comment by TechsUsInc** [comment]
Please see #2356

**Comment by TechsUsInc** [comment]
Please see #2357

**Comment by TechsUsInc** [comment]
Please see #2358

**Comment by TechsUsInc** [comment]
Please see #2359

**Comment by TechsUsInc** [comment]
Please see #2366

**Comment by TechsUsInc** [comment]
Please see #2389

**Comment by TechsUsInc** [comment]
Please see #2390

**Comment by TechsUsInc** [comment]
Please see #2396

**Comment by sschiessl-bcp** [comment]
You were on fire, and thank you!

**Comment by TechsUsInc** [comment]
> You were on fire, and thank you!

thank you. 
Please see #2402

**Comment by wmbutler** [comment]
Please post your bts payment address.

**Comment by sschiessl-bcp** [comment]
See here https://github.com/bitshares/bitshares-ui/issues/2274#issuecomment-453884839, bottom of first page

**Comment by TechsUsInc** [comment]
> Please post your bts payment address.

lil-bi.t-of-techs-us

**Comment by TechsUsInc** [comment]
> Please post your bts payment address

@wmbutler Can you check the status please.
I pinged you because I don't think the above was followed upon iirc.

1. Integration testing 1 - comp received iirc
2. Integration testing 2 - see above comments; comp still pending
3. Integration testing 3 - status unknown
