### ISSUE TITLE
[2.0.181212-rc1] Integration testing by toi16

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2281]
Reference https://github.com/bitshares/bitshares-ui/issues/2274

**Comment by toi16** [comment]
My OS:
Windows 10, Version: 1803 (OS Build 17134.407)

My Browser:
Chrome, Version 71.0.3578.80 (Official Build) (64-bit)

General 
 - [ ] Wallet loads and connects
 - [ ] Login via cloud login and local wallet
 - [ ] Transfer between accounts
 - [ ] Exchange opens, orders are visible and limit orders can be put
 - [ ] Margin creation and adjustment is possible
 - [ ] Voting is possible (committee, witness, proposals)

Specific components:
 - [ ] #2221 Collateral Bidding
    - Find the collateral bid overview, test in small and big browser size. Try to add a bid (you may cancel before broadcasting), optionally add and remove a bid
 - [ ] #2023 Create a paper wallet, with and without private keys
 - [ ] #2127 View the margin position table in the dashboard, are all rows displayed properly and loaded correctly?
 - [ ] #2224 Attempt to settle any amount of bitUSD (settlement button in exchange and margin position table in dashboard). Does the modal open correctly? Are the values presented properly, and the price overview correct? Optionally, do actually settle any amount of bitUSD

**Comment by toi16** [comment]
My OS:
Windows 10, Version: 1803 (OS Build 17134.407)

My Browser:
Firefox, Version: 63.0.3 (64-bit)

General 
 - [ ] Wallet loads and connects
 - [ ] Login via cloud login and local wallet
 - [ ] Transfer between accounts
 - [ ] Exchange opens, orders are visible and limit orders can be put
 - [ ] Margin creation and adjustment is possible
 - [ ] Voting is possible (committee, witness, proposals)

Specific components:
 - [ ] #2221 Collateral Bidding
    - Find the collateral bid overview, test in small and big browser size. Try to add a bid (you may cancel before broadcasting), optionally add and remove a bid
 - [ ] #2023 Create a paper wallet, with and without private keys
 - [ ] #2127 View the margin position table in the dashboard, are all rows displayed properly and loaded correctly?
 - [ ] #2224 Attempt to settle any amount of bitUSD (settlement button in exchange and margin position table in dashboard). Does the modal open correctly? Are the values presented properly, and the price overview correct? Optionally, do actually settle any amount of bitUSD

**Comment by toi16** [comment]
Bug Report Logged: [2.0.181212-rc1] Integration testing by toi16 - File Manager Issue loading bin file https://github.com/bitshares/bitshares-ui/issues/2282

**Comment by toi16** [comment]
Bug Report Logged: [2.0.181212-rc1] Integration testing by toi16 - Margin Table Alignment. https://github.com/bitshares/bitshares-ui/issues/2283

**Comment by toi16** [comment]
Bug Report Logged: [2.0.181212-rc1] Integration testing by toi16 - Settlement UI Issues. https://github.com/bitshares/bitshares-ui/issues/2284

**Comment by toi16** [comment]
With regards to the 'Paper Wallet' feature, I would suggest making the sentence:
 'If the wallet is unlocked, the private keys are added as well.'
more prominent to the user so that they are clear that your private keys are printed if your wallet is unlocked. 
This could be implemented by using a different font colour and background to hi-light it.

Also on the subject of printing the resulting PDF, the end user should be made aware that printing the information using a networked / cloud printer could compromise the private keys as the print jobs are usually cached. Maybe add this warning to the PDF copy ??.

**Comment by sschiessl-bcp** [comment]
Thank you
