### ISSUE TITLE
[3][OpenLedgerApp] Style Guide implementation on Sign-in/Sign-up related sub-pages

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/bitshares-ui#2297]
**Describe the bug**
1. Data input field color is barely visible against the background black (throughout the entire interface)
2. _Restore Backup submit button_ is white instead of blue (submit text is barely visible)
3. Design theme is not consistent with the _back_, _reset_, other buttons (throughout the interface)

**To Reproduce**
1. From the _welcome to bitshares page_;
![welcome_to_bitshares_landing_1_capture](https://user-images.githubusercontent.com/18186497/49713590-0269d780-fc0f-11e8-89cb-1c08684cb665.JPG)
Click on the blue text _Restore your account_ ; note that the input text field is very dark, hard to see, shade is too close to the background shade (account and password fields)
![bts_advanced_login_capture_1](https://user-images.githubusercontent.com/18186497/49702378-1553bc00-fbbd-11e8-80b2-7d7850dda794.JPG)![181212-rc1_welcome_to_bitshares_restore_backup_1_capture](https://user-images.githubusercontent.com/18186497/49702840-e3ddef00-fbc2-11e8-9761-1a7061a07005.JPG)
2. scroll down to _restore local wallet from backup_ and click it; note the _back button_ modal colors 
   (text and background)
![181212-rc1_back_button_capture](https://user-images.githubusercontent.com/18186497/49702863-3ddeb480-fbc3-11e8-95c3-c37d0d7f7d65.JPG)
In my opinion this looks best;which-ever design is chosen should be consistent throughout the interface. Please consider applying the same rule to the _reset button_
3. Click the _back_ button returning to the _Welcome to Bitshares_ page
![welcome_to_bitshares_landing_1_capture](https://user-images.githubusercontent.com/18186497/49713462-663fd080-fc0e-11e8-8954-0760073f9265.JPG) 
4. Click on _Advanced Form_ in blue text
![bts_advanced_login_capture_1](https://user-images.githubusercontent.com/18186497/49713689-6b514f80-fc0f-11e8-9cf3-41fe3254adea.JPG)
5. Again, note the account and password input fields are too dark, hardly visible against the black 
    background 
6. In blue text, click _restore using a local wallet brainkey_
![181212-rc1_restore_using_a_brainkey_1_capture](https://user-images.githubusercontent.com/18186497/49714312-06e3bf80-fc12-11e8-9cbf-a597e44079e4.JPG)
Consider using the same theme as this back button for cancel
![181212-rc1_back_button_capture](https://user-images.githubusercontent.com/18186497/49714384-3c88a880-fc12-11e8-9097-d70a4b12c47b.JPG)

**Expected behavior**
Consistent design and color
Easily visible text entry fields

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Browser Opera
 - Version 56.0.3051.116

**Comment by startailcoon** [comment]
As we have the new login/signup from #2210 implemented, we should visit this task to make the rest of the correlated sections of the app look better.

Especially, as mentioned, the button and form should be using the new Style Guide.

### Tasks
- Make the related sections to sign-up/sign-in follow the Style Guide with form, buttons etc.

**Comment by OpenLedgerApp** [comment]
@startailcoon, we can take this one.

**Comment by startailcoon** [comment]
@OpenLedgerApp sorry for the delay, missed your comment.

This issue relates to the following routes 

- /wallet/backup/restore
- /existing-account
- /create-wallet-brainkey

It should
- [ ] Replace all old components with new style-guide.
- [ ] Make sure all components are visible correctly.
- [ ] Should refer to FAQ sections, like `/help/introduction/wallets` for the user to read more about the wallet, and also possibly `/help/introduction/backups`.

**Comment by OpenLedgerApp** [comment]
@startailcoon, sorry, it seems there is a misunderstanding about the last item "Should refer to FAQ sections".
Do you mean that (/help/introduction/wallets, /help/introduction/backups) should be links?
If yes, which routes and what names of the links should be (for example, "help" with question icon like in the header dropdown or smth else)?

**Comment by startailcoon** [comment]
@OpenLedgerApp I would say that a `?` symbol is to vague at this place. 

I'd say that we add a paragraph after the text, but before the form, stating `Read more about (wallet types) and (backup types)` where the text within `()` links to the pages.

**Comment by startailcoon** [comment]
> 
> 
> @OpenLedgerApp I would say that a `?` symbol is to vague at this place.
> 
> I'd say that we add a paragraph after the text, but before the form, stating `Read more about (wallet types) and (backup types)` where the text within `()` links to the pages.

I see you added the links within () signs. That was just a way to explain which parts where supposed to be clickable. We should remove those again without the () around them.
