### ISSUE TITLE
[2.0.181212-rc1] Integration testing by Kennybll

### ISSUE THREAD

**Issue by Kennybll** [bitshares/bitshares-ui#2334]
My OS:
  - Android 7.1.1 (Nougat)

My Browser:
 - Firefox 63.0.2

General 
 - [x] Wallet loads and connects
 - [ ] Login via cloud login and local wallet
 - [ ] Transfer between accounts
 - [ ] Exchange opens, orders are visible and limit orders can be put
 - [ ] Margin creation and adjustment is possible
 - [ ] Voting is possible (committee, witness, proposals)

Specific components:
 - [ ] #2221 Collateral Bidding
    - Find the collateral bid overview, test in small and big browser size. Try to add a bid (you may cancel before broadcasting), optionally add and remove a bid
 - [ ] #2023 Create a paper wallet, with and without private keys
 - [ ] #2127 View the margin position table in the dashboard, are all rows displayed properly and loaded correctly?
 - [ ] #2224 Attempt to settle any amount of bitUSD (settlement button in exchange and margin position table in dashboard). Does the modal open correctly? Are the values presented properly, and the price overview correct? Optionally, do actually settle any amount of bitUSD

**Comment by Kennybll** [comment]
https://github.com/bitshares/bitshares-ui/issues/2335

**Comment by sschiessl-bcp** [comment]
Did you test this throughout all checkboxes?
