### ISSUE TITLE
[2.0.190207-rc2] Integration tests

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2436]
<h1>Disclaimer</h1>

The UI worker is currently underfunded, a new one is one the way but not posted yet. Please be aware that any testing might end up being volunteer work.

Release notes of the corresponding candidate can be found here:
https://github.com/bitshares/bitshares-ui/releases/tag/2.0.190207-rc2

<h1>Looking for Integration testers</h1>

This issue is to track integration tests of the mentioned release candidate. Targets are the most popular platforms
 - Mac
 - Windows 7 / 10
 - Linux
 - Android
 - iOS

and for each for the most popular browsers
 - Chrome
 - Firefox
 - Opera
 - Edge
 - Standard Android / iOS browser

Please indicate which of those you are able to test, expectancy is 0.5 hours per platform / browser. Reports are mandatory and must be done for every browser and platform. If you are interested in doing integration tests please do the following:

1. Choose your OS(s) and browser(s) and indicate with a comment that you are interested
2. Wait to be approved by the UI team, a new issue will be created by us for your testing
3. Copy the below template in the new issue that was created for you, for each OS/browser pair
3. Tick the checkboxes in your comment while doing the integration test for each OS/browser pair 

If you find any problems in rendering, error messages or simply weird behavior in the functionality listed in this issue, please report them as a [separate issue in github](https://github.com/bitshares/bitshares-ui/issues) and add a link as comment in the new issue that was created for you. Every issue must include a way how to reproduce them, what the error (please get familiar with how to obtain browser console logs) is and what an expected solution is. Reported issues that are accepted by the UI team will be added as bonus 0.1 hours for your payout.

<h1>Reporting</h1>
Copy everything in the box in your comment as template for the report, only one browser / OS per report

```
My OS:
  - Mac/Windows/Linux/Android/iOS, Version: <version>

My Browser:
 - Chrome/Firefox/Opera/Edge/etc., Version: <version>

General 
 - [ ] Wallet loads and connects
 - [ ] Login via cloud login and local wallet
 - [ ] Transfer between accounts
 - [ ] Exchange opens, orders are visible and limit orders can be put
 - [ ] Margin creation and adjustment is possible
 - [ ] Voting is possible (committee, witness, proposals)

Specific components:
 - [ ] #1859 #2408 Spotlight: Barter the hell out of it
 - [ ] #2232 Read through the CDB description, ask if anything is unclear (important!)
 - [ ] Export your account history and check the details (go to Dashboard > Activity)
 - [ ] #2386 Play around with new login option and the focus behavior
 - [ ] #2151 Click around in exchange, buy/sell, personalize and check the browser console log for error, report if any
```

**Comment by TechsUsInc** [comment]
My OS:
Windows, Version: 8.1 (Primary)
Windows, Version 10
Linux Ubuntu Version 16.04
Linux Ubuntu Version 18.04
Android 7.1.1 (Nougat)

My Browser:
Opera 56.0.3051.116 (Primary)
Google Version 70.0.3538.110 (Official Build) (64-bit)
Firefox Version 63.0.3(64-bit)
Brave Version 0.25.2 V8 6.9.427.23 OS Release 6.3.9600
Bitorrent Version 7.10.4.44847
General 
 - [ ] Wallet loads and connects
 - [ ] Login via cloud login and local wallet
 - [ ] Transfer between accounts
 - [ ] Exchange opens, orders are visible and limit orders can be put
 - [ ] Margin creation and adjustment is possible
 - [ ] Voting is possible (committee, witness, proposals)

Specific components:
 - [ ] #1859 #2408 Spotlight: Barter the hell out of it
 - [ ] #2232 Read through the CDB description, ask if anything is unclear (important!)
 - [ ] Export your account history and check the details (go to Dashboard > Activity)
 - [ ] #2386 Play around with new login option and the focus behavior
 - [ ] #2151 Click around in exchange, buy/sell, personalize and check the browser console log for error, report if any

**Comment by sschiessl-bcp** [comment]
@TechsUsInc 
Please go ahead with 
 - Windows, Version 10, Brave
 - Linux Ubuntu Version 18.04, Brave
 - Linux Ubuntu Version 18.04, Version 10, Firefox
 - Android, any browser of your choosing

**Comment by TechsUsInc** [comment]
> @TechsUsInc
> Please go ahead with
> 
> * Windows, Version 10, Brave
> * Linux Ubuntu Version 18.04, Brave
> * Linux Ubuntu Version 18.04, Version 10, Firefox
> * Android, any browser of your choosing
> 
> Your isse #2440

Message received.

**Comment by TechsUsInc** [comment]
My OS:
Windows, Version: 8.1 (Primary)
Windows, Version 10

My Browser:
 Brave Version 0.25.2 V8 6.9.427.23 OS Release 6.3.9600
General 
 - [ ] Wallet loads and connects
 - [ ] Login via cloud login and local wallet
 - [ ] Transfer between accounts
 - [ ] Exchange opens, orders are visible and limit orders can be put
 - [ ] Margin creation and adjustment is possible
 - [ ] Voting is possible (committee, witness, proposals)

Specific components:
 - [ ] #1859 #2408 Spotlight: Barter the hell out of it
 - [ ] #2232 Read through the CDB description, ask if anything is unclear (important!)
 - [ ] Export your account history and check the details (go to Dashboard > Activity)
 - [ ] #2386 Play around with new login option and the focus behavior
 - [ ] #2151 Click around in exchange, buy/sell, personalize and check the browser console log for error, report if any

**Comment by TechsUsInc** [comment]
My OS:
 Linux Ubuntu Version 18.04

My Browser:
Brave Version 0.25.2 V8 6.9.427.23 OS Release 6.3.9600

General 
 - [ ] Wallet loads and connects
 - [ ] Login via cloud login and local wallet
 - [ ] Transfer between accounts
 - [ ] Exchange opens, orders are visible and limit orders can be put
 - [ ] Margin creation and adjustment is possible
 - [ ] Voting is possible (committee, witness, proposals)

Specific components:
 - [ ] #1859 #2408 Spotlight: Barter the hell out of it
 - [ ] #2232 Read through the CDB description, ask if anything is unclear (important!)
 - [ ] Export your account history and check the details (go to Dashboard > Activity)
 - [ ] #2386 Play around with new login option and the focus behavior
 - [ ] #2151 Click around in exchange, buy/sell, personalize and check the browser console log for error, report if any

**Comment by xiaolujidan** [comment]
@sschiessl-bcp 
I know little about it
I can use  https://staging.bitshares.org Address of the test.
Or how to get started quickly.
Is there documentation of the testing process

**Comment by sschiessl-bcp** [comment]
The only documentation that exists right now is the [header of this issue](https://github.com/bitshares/bitshares-ui/issues/2436#issue-405699273).

What kind of introduction would you like, what questions do you have?

**Comment by xiaolujidan** [comment]
My OS:
  Windows, Version 10

My Browser:
 Google Version 69.0.3493.3 (official) (32-bit)
 Firefox Version  61.0.2 (64-bit)
General 
 - [ ] Wallet loads and connects
 - [ ] Login via cloud login and local wallet
 - [ ] Transfer between accounts
 - [ ] Exchange opens, orders are visible and limit orders can be put
 - [ ] Margin creation and adjustment is possible
 - [ ] Voting is possible (committee, witness, proposals)

Specific components:
 - [ ] #1859 #2408 Spotlight: Barter the hell out of it
 - [ ] #2232 Read through the CDB description, ask if anything is unclear (important!)
 - [ ] Export your account history and check the details (go to Dashboard > Activity)
 - [ ] #2386 Play around with new login option and the focus behavior
 - [ ] #2151 Click around in exchange, buy/sell, personalize and check the browser console log for error, report if any

**Comment by xiaolujidan** [comment]
I create accounts directly through the main network.
![image](https://user-images.githubusercontent.com/41559541/52680580-e4548680-2f73-11e9-830f-df637a56fd2b.png)

What should I do next

**Comment by xiaolujidan** [comment]
The desktop version error
![image](https://user-images.githubusercontent.com/41559541/52694570-192d0180-2fa5-11e9-9614-e6c54a51f0f8.png)

**Comment by sschiessl-bcp** [comment]
Please open a new issue and describe exactly what you did to get to that point

**Comment by startailcoon** [comment]
My OS:
  - Windows 10, Version: 1803, 17134.523

My Browser:
 - Firefox., Version: 65.0 (64-bit)

General 
 - [x] Wallet loads and connects (see additional issues below)
 - [x] Login via cloud login and local wallet (see additional issues below)
 - [x] Transfer between accounts
 - [x] Exchange opens, orders are visible and limit orders can be put and canceled
 - [x] Margin creation and adjustment is possible
 - [x] Voting is possible (committee, witness, proposals), adding and removing Proxy possible

Specific components:
 - [x] #1859 #2408 Spotlight: Barter the hell out of it
 - [ ] #2232 Read through the CDB description, ask if anything is unclear (important!)
 - [ ] Export your account history and check the details (go to Dashboard > Activity)
 - [ ] #2386 Play around with new login option and the focus behavior
 - [ ] #2151 Click around in exchange, buy/sell, personalize and check the browser console log for error, report if any

## Addition Reports

#### Startup
- Failed required checks
```
Warning: Failed value type: The value `isRequired` is marked as required in `Select`, but its value is `undefined`. checkPropTypes.js:19
Warning: Failed defaultValue type: The defaultValue `isRequired` is marked as required in `Select`, but its value is `undefined`. checkPropTypes.js:19 
```

- Unreachable code on `AccountNameInputStyleGuide.jsx:181`
- Unreachable code on `Barter.jsx:840`
- Unreachable code on `Barter.jsx:904`

#### Login
- Trying to login without a username will highlight password field as error regardless
- Login cloud with `Rember me` false, will not do anything. Username still filled in next time.

#### Exchange
- Introduction still does not scrollthe page if highlighted item is outside the scope of the window. A blank background is visible with the highlighted area and text.

### Showcase: Barter
- Unable to click amount on asset select to use all
- Perhaps a note that Escrow Memo can't be read by Peer 2?
- Possible to set Peer 1 + Escrow as the same account.
- Possible to set Peer 2 + Escrow as the same account.

**Comment by sschiessl-bcp** [comment]
> * Unreachable code on `AccountNameInputStyleGuide.jsx:181`
> * Unreachable code on `Barter.jsx:840`
> * Unreachable code on `Barter.jsx:904`

Can you please specify (screenshot or permalink) what lines those are?

**Comment by sschiessl-bcp** [comment]
> * Trying to login without a username will highlight password field as error regardless

![image](https://user-images.githubusercontent.com/33128181/53085378-01083580-3503-11e9-872d-57049345adeb.png)

Can you please specify how to reproduce?

**Comment by sschiessl-bcp** [comment]
Closed, release is published

**Comment by sschiessl-bcp** [comment]
Thanks to everyone for participating. Payouts should have been received now.
