### ISSUE TITLE
[2.0.190207-rc2] Integration tests by @TechUsInc

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2440]
For reference, #2436

**Comment by TechsUsInc** [comment]
My OS:
 Windows, Version: 8.1 (Primary)
Windows, Version 10

My Browser:
Brave Version 0.25.2 V8 6.9.427.23 OS Release 6.3.9600

General 
 - [ ] Wallet loads and connects
 - [ ] Login via cloud login and local wallet
 - [ ] Transfer between accounts
 - [ ] Exchange opens, orders are visible and limit orders can be put
 - [ ] Margin creation and adjustment is possible
 - [ ] Voting is possible (committee, witness, proposals)

Specific components:
 - [ ] #1859 #2408 Spotlight: Barter the hell out of it
 - [ ] #2232 Read through the CDB description, ask if anything is unclear (important!)
 - [ ] Export your account history and check the details (go to Dashboard > Activity)
 - [ ] #2386 Play around with new login option and the focus behavior
 - [ ] #2151 Click around in exchange, buy/sell, personalize and check the browser console log for error, report if any

**Comment by TechsUsInc** [comment]
My OS:
  Linux Ubuntu Version 18.04

My Browser:
Firefox Version 63.0.3(64-bit)
Brave Version 0.25.2 V8 6.9.427.23 OS Release 6.3.9600

General 
 - [ ] Wallet loads and connects
 - [ ] Login via cloud login and local wallet
 - [ ] Transfer between accounts
 - [ ] Exchange opens, orders are visible and limit orders can be put
 - [ ] Margin creation and adjustment is possible
 - [ ] Voting is possible (committee, witness, proposals)

Specific components:
 - [ ] #1859 #2408 Spotlight: Barter the hell out of it
 - [ ] #2232 Read through the CDB description, ask if anything is unclear (important!)
 - [ ] Export your account history and check the details (go to Dashboard > Activity)
 - [ ] #2386 Play around with new login option and the focus behavior
 - [ ] #2151 Click around in exchange, buy/sell, personalize and check the browser console log for error, report if any

**Comment by TechsUsInc** [comment]
My OS:
 Android 7.1.1 (Nougat)

My Browser:
Opera 56.0.3051.116 (Primary)

General 
 - [ ] Wallet loads and connects
 - [ ] Login via cloud login and local wallet
 - [ ] Transfer between accounts
 - [ ] Exchange opens, orders are visible and limit orders can be put
 - [ ] Margin creation and adjustment is possible
 - [ ] Voting is possible (committee, witness, proposals)

Specific components:
 - [ ] #1859 #2408 Spotlight: Barter the hell out of it
 - [ ] #2232 Read through the CDB description, ask if anything is unclear (important!)
 - [ ] Export your account history and check the details (go to Dashboard > Activity)
 - [ ] #2386 Play around with new login option and the focus behavior
 - [ ] #2151 Click around in exchange, buy/sell, personalize and check the browser console log for error, report if any

**Comment by TechsUsInc** [comment]
My OS:
 - Linux Ubuntu Version: <Ubuntu18.04>

My Browser:
 - Brave Version: <Brave 0.25.2 V8 6.9.427.23 OS Release 6.3.9600>

General 
 - [ ] Wallet loads and connects
 - [ ] Login via cloud login and local wallet
 - [ ] Transfer between accounts
 - [ ] Exchange opens, orders are visible and limit orders can be put
 - [ ] Margin creation and adjustment is possible
 - [ ] Voting is possible (committee, witness, proposals)

Specific components:
 - [ ] #1859 #2408 Spotlight: Barter the hell out of it
 - [ ] #2232 Read through the CDB description, ask if anything is unclear (important!)
 - [ ] Export your account history and check the details (go to Dashboard > Activity)
 - [ ] #2386 Play around with new login option and the focus behavior
 - [ ] #2151 Click around in exchange, buy/sell, personalize and check the browser console log for error, report if any

**Comment by xiaolujidan** [comment]
Excuse me，Where can I find information for beginners，I don't know how to get started，Can I test the whole process

**Comment by TechsUsInc** [comment]
@xiaolujidan Welcome to the community where any and all contributions are encouraged. Good luck.

Please refer to the documentation at the following links firstly to gain a solid understanding. Additional resources available are provided from various sources and require doing your own research and validation.
http://how.bitshares.works/en/master/
Bitsharestalk.org
https://t.me/BitSharesDEX

Upon reaching a clear understanding, please then refer to the following directive
https://github.com/bitshares/bitshares-ui/issues/2436

**Comment by xiaolujidan** [comment]
I went through all the documents,But I still couldn't figure out how to start testing
Still stay in their own private chain environment, failed to start process testing

**Comment by xiaolujidan** [comment]
@TechsUsInc   
My knowledge in this field is superficial.I read the following
http://how.bitshares.works/en/master/
https://dev.bitshares.works
https://bitsharestalk.org/index.php
The test flow could not be found

**Comment by TechsUsInc** [comment]
Please see #2461

**Comment by TechsUsInc** [comment]
approx 50 BTS testing lil-bi.t-of-techs-us

**Comment by TechsUsInc** [comment]
Please see #2462

**Comment by TechsUsInc** [comment]
Please see #2463

**Comment by TechsUsInc** [comment]
Please see #2464

**Comment by TechsUsInc** [comment]
Please see #2465

**Comment by TechsUsInc** [comment]
Please see #2466

**Comment by TechsUsInc** [comment]
Please see #2467

**Comment by TechsUsInc** [comment]
Please see #2468

**Comment by TechsUsInc** [comment]
Please see #2469

**Comment by TechsUsInc** [comment]
Please see #2470

**Comment by TechsUsInc** [comment]
Please see #2471

**Comment by TechsUsInc** [comment]
Please see #2472

**Comment by TechsUsInc** [comment]
Please see #2473

**Comment by TechsUsInc** [comment]
Please see #2474

**Comment by TechsUsInc** [comment]
Please see #2475

**Comment by TechsUsInc** [comment]
Please see #2490

**Comment by TechsUsInc** [comment]
Please see #2491 2491

**Comment by TechsUsInc** [comment]
Please see #2492

**Comment by TechsUsInc** [comment]
Please see #2493

**Comment by TechsUsInc** [comment]
Please see #2494

**Comment by sschiessl-bcp** [comment]
You have 4 reports in this issue, but 2 are not filled out. Were they done and did not work?

**Comment by TechsUsInc** [comment]
Completed. 
Any issues captured/reported.

**Comment by sschiessl-bcp** [comment]
Bounty: 2 (4 platforms/OS) + 1.8 (reported & accepted issues #2461 #2464 #2465 #2466 #2468 #2469 #2471 #2472 #2475 #2467 #2470 #2473 #2474 #2490 #2491 #2492 #2493 #2494) + 0.1 (transaction fee expenses for bartering)
