### ISSUE TITLE
[2.0.190410-rc1] Integration Testing

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2557]
Release notes of the corresponding candidate can be found here:
https://github.com/bitshares/bitshares-ui/releases/tag/2.0.190410-rc1

<h1>Looking for Integration testers</h1>

This issue is to track integration tests of the mentioned release candidate. Targets are the most popular platforms
 - Mac
 - Windows 7 / 10
 - Linux
 - Android
 - iOS

and for each for the most popular browsers
 - Chrome
 - Firefox
 - Opera
 - Edge
 - Standard Android / iOS browser

Please indicate which of those you are able to test, expectancy is 0.5 hours per platform / browser. Reports are mandatory and must be done for every browser and platform. If you are interested in doing integration tests please do the following:

1. Choose your OS(s) and browser(s) and indicate with a comment that you are interested
2. Wait to be approved by the UI team, then create a new issue for your testing, name it `[2.0.190410-rc1] Integration Tests by <yourgithubname>`
3. Copy the below template in the new issue that was created for you, for each OS/browser pair
3. Tick the checkboxes in your comment while doing the integration test for each OS/browser pair 

If you find any problems in rendering, error messages or simply weird behavior in the functionality listed in this issue, please report them as a [separate issue in github](https://github.com/bitshares/bitshares-ui/issues) and add a link as comment in the new issue that was created for you. Every issue must include a way how to reproduce them, what the error (please get familiar with how to obtain browser console logs) is and what an expected solution is. Reported issues that are accepted by the UI team will be added as bonus 0.1 hours for your payout. If you have significant (but necessary) costs for conducting the tests in terms of BTS for transaction fees, please state them as well and you will be reimbursed.

<h1>Reporting</h1>
Copy everything in the box in your comment as template for the report, only one browser / OS per report

```
My OS:
  - Mac/Windows/Linux/Android/iOS, Version: <version>

My Browser:
 - Chrome/Firefox/Opera/Edge/etc., Version: <version>

General 
 - [ ] Wallet loads and connects
 - [ ] Login via cloud login and local wallet
 - [ ] Transfer between accounts (with and without memo)
 - [ ] Exchange opens, orders are visible and limit orders can be put
 - [ ] Margin creation and adjustment is possible
 - [ ] Voting is possible (committee, witness, proposals)

Specific components:
 - [ ] Scaled Orders #1503 #2497: Put a scaled order with at least 3 single orders, both on buy and sell end
 - [ ] Direct Debit Authorization #2457: Create, update and claim a direct debit authorization. Then cancel it
 - [ ] #2531 Create a proposal and check that the proposer is shown, both on Activity tab and Proposed Transactions tab
 - [ ] #2386 Play around with new login option and the focus behavior
 - [ ] Optional: #2487 Deposit and withdraw using BTC using your favorite gateway. Gateway fees will be reimbursed, must be shown.
 - [ ] #2559 Delete cache, observe how the ping is accelerated. Furthermore go to Settings > Nodes and ping manually, observe the full cycle.
```

**Comment by TechsUsInc** [comment]
My OS:
- Windows, Version: 8.1 (Primary)
-  Windows, Version 10
- Linux Ubuntu Version 16.04
- Linux Ubuntu Version 18.04
- Android 7.1.1 (Nougat)
- Apple IOS 


My Browser:
- Opera 58.0.3135.127 (Primary)
- Google Version  73.0.3683.86 (Official Build) (64-bit)
- Firefox Version 63.0.3(64-bit)
- Brave Version 0.25.2 V8 6.9.427.23 OS Release 6.3.9600
- Bitorrent Version 7.10.4.44847

**Comment by froooze** [comment]
My OS:
- MX-Linux 18.1

My Browser:
- Firefox 66.0.2
- Chromium 72.0
- Opera 58

**Comment by sschiessl-bcp** [comment]
@TechsUsInc Please go ahead with 
 - Windows 8.1, Opera and Firefox
 - Linux Ubuntu Version 16.04, Chrome and Firefox

@froooze Please go ahead with 
 - MX-Linux 18.1, Firefox and Chromium

**Comment by sschiessl-bcp** [comment]
Thanks for participating, this is closed now.
