### ISSUE TITLE
[0.5][2.0.190410-rc1] Integration Tests with Firefox by <frooze>

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2596]
My OS:
  - MX-Linux 18.1

My Browser:
 - Firefox 66

General 
 - [x] Wallet loads and connects
 - [x] Login via cloud login and local wallet
 - [x] Transfer between accounts (with and without memo)
 - [x] Exchange opens, orders are visible and limit orders can be put
 - [x] Margin creation and adjustment is possible
 - [x] Voting is possible (committee, witness, proposals)

Specific components:
 - [x] Scaled Orders #1503 #2497: Put a scaled order with at least 3 single orders, both on buy and sell end
 - [x] Direct Debit Authorization #2457: Create, update and claim a direct debit authorization. Then cancel it
 - [x] #2531 Create a proposal and check that the proposer is shown, both on Activity tab and Proposed Transactions tab
 - [x] #2386 Play around with new login option and the focus behavior
 - [ ] Optional: #2487 Deposit and withdraw using BTC using your favorite gateway. Gateway fees will be reimbursed, must be shown.
 - [x] #2559 Delete cache, observe how the ping is accelerated. Furthermore go to Settings > Nodes and ping manually, observe the full cycle.

**Comment by sschiessl-bcp** [comment]
Were any issues reporting during that?

**Comment by froooze** [comment]
No extra issues.
