### ISSUE TITLE
Reserve fund spending allocation visualiser

### ISSUE THREAD

**Issue by CryptoKong** [bitshares/bitshares-ui#2682]
**Is your feature request related to a problem? Please describe.**
Not enough information on allocated active worker spending

**Describe the solution you'd like**
Have information available on a chart how reserve funds are being spent

**Additional context**
Create a page for charts that split spending up into groups over each financial year and the previous years for comparison. Then users can see how much of reserve pool funds are being allocated to marketing, core development, infrastructure, UI, market making or efforts to improve market conditions, etc.

**Comment by mistdale** [comment]
Makes the system transparent, that would be really helpful.

**Comment by bitfanatic** [comment]
Love the idea kong

And While we are brushing up on the voting page 

Making improvements to witness pane and committee pane would be nice to do aswell

Giving the ability to tell who they are and what they stand for on the bitshares website 
Would make it look more serious 

And could add how they have voted in the past on different workers and witnesses and commitee members

**Comment by startailcoon** [comment]
Indeed a nice idea. Bitshares is a transparent system, and we should try to view as much information as possible towards visualizing this.

Most of the time for this issue would be to summarize where to find all the data and request changes to fetch any missing data. Together with the below attached chart we should supply a table of each type and summarize nicely for the user.

We should investigate what types of data we can fetch from chain today and what we need core team to look at. 

From [Bitshares.works](https://dev.bitshares.works) > [Docs » BitShares Accounts » Fees](https://dev.bitshares.works/en/master/bts_guide/accounts/bts_fees.html)
<img src='https://dev.bitshares.works/en/master/_images/BitShares-Cashflow2.png'>

# Tasks

### UX Tasks
- [ ] Visualize supplied data to end user based on "Cash Flow" chart.

### UI Tasks
- [ ] Locate chain objects to fetch required data
- [ ] Locate ES objects to fetch required data
- [ ] Request and communicate with core/ES team to implement required data
- [ ] Implement route for visualizing "Cash Flow" table
