### ISSUE TITLE
[2][3.1.190618-rc1] Integration Testing

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#2753]
Release notes of the corresponding candidate can be found here:
https://github.com/bitshares/bitshares-ui/issues/2641

<h1>Looking for Integration testers</h1>

This issue is to track integration tests of the mentioned release candidate. Targets are the most popular platforms
 - Mac
 - Windows 7 / 10
 - Linux
 - Android
 - iOS

and for each for the most popular browsers
 - Chrome
 - Firefox
 - Opera
 - Edge
 - Standard Android / iOS browser

Please indicate which of those you are able to test, expectancy is 0.5 hours per platform / browser. Reports are mandatory and must be done for every browser and platform. If you are interested in doing integration tests please do the following:

1. Choose your OS(s) and browser(s) and indicate with a comment that you are interested
2. Wait to be approved by the UI team, then create a new issue for your testing, name it `[3.1.190618-rc1] Integration Tests by <yourgithubname>`
3. Copy the below template in the new issue that was created for you, for each OS/browser pair
3. Tick the checkboxes in your comment while doing the integration test for each OS/browser pair 

If you find any problems in rendering, error messages or simply weird behavior in the functionality listed in this issue, please report them as a [separate issue in github](https://github.com/bitshares/bitshares-ui/issues) and add a link as comment in the new issue that was created for you. Every issue must include a way how to reproduce them, what the error (please get familiar with how to obtain browser console logs) is and what an expected solution is. Reported issues that are accepted by the UI team will be added as bonus 0.1 hours for your payout. If you have significant (but necessary) costs for conducting the tests in terms of BTS for transaction fees, please state them as well and you will be reimbursed.

<h1>Reporting</h1>
Copy everything in the box in your comment as template for the report, only one browser / OS per report

```
My OS:
  - Mac/Windows/Linux/Android/iOS, Version: <version>

My Browser:
 - Installed Light client/Chrome/Firefox/Opera/Edge/etc., Version: <version>

General 
 - [ ] Wallet loads and connects
 - [ ] Login via cloud login and local wallet
 - [ ] Transfer between accounts (with and without memo)
 - [ ] Exchange opens, orders are visible and limit orders can be put
 - [ ] Margin creation and adjustment is possible
 - [ ] Voting is possible (committee, witness, proposals)

Specific components:
 - [ ] Test HTCL functionality (create, extend and redeem) #2589 #2643 
   - [ ] Optional for bonus points [0.5]: Do an atomic cross chain swap with another blockchain. Ping us for support if needed
 - [ ] Make a proposal and check the verbose output, and reject it #2499 #2527 
 - [ ] Find the new Poll/BSIP section in voting panel and vote on something #2626
 - [ ] Export both types for account activities #2543
 - [ ] Cancel multiple orders in Exchange #2317
 - 
```

**Comment by froooze** [comment]
I can test on Linux:
- Light Client
- Firefox
- Chromium
- Opera

**Comment by sschiessl-bcp** [comment]
@froooze please go ahead with light client and firefox

**Comment by froooze** [comment]
Where can I find the download link for light client RC ?

**Comment by sschiessl-bcp** [comment]
Github releases
