### ISSUE TITLE
[3.1.190618-rc1] Integration Tests by [frooze] for Firefox

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2769]
My OS:
  - MX-Linux

My Browser:
 - Firefox 67.0.2

General 
 - [x] Wallet loads and connects
 - [x] Login via cloud login and local wallet
 - [x] Transfer between accounts (with and without memo)
 - [x] Exchange opens, orders are visible and limit orders can be put
 - [x] Margin creation and adjustment is possible
 - [x] Voting is possible (committee, witness, proposals)

Specific components:
 - [x] Test HTCL functionality (create, extend and redeem) #2589 #2643 
 - [ ] Optional for bonus points [0.5]: Do an atomic cross chain swap with another blockchain. Ping us for support if needed
 - [x] Make a proposal and check the verbose output, and reject it #2499 #2527 
 - [x] Find the new Poll/BSIP section in voting panel and vote on something #2626
 - [x] Export both types for account activities #2543
 - [x] Cancel multiple orders in Exchange #2317
