### ISSUE TITLE
[5][3.1.190618-rc1] Integration Tests by [frooze] for Light client

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2771]
For #2753

My OS:
  - MX-Linux

My Browser:
 - Light client 

General 
 - [x] Wallet loads and connects
 - [x] Login via cloud login and local wallet
 - [x] Transfer between accounts (with and without memo)
 - [x] Exchange opens, orders are visible and limit orders can be put
 - [x] Margin creation and adjustment is possible
 - [x] Voting is possible (committee, witness, proposals)

Specific components:
 - [x] Test HTCL functionality (create, extend and redeem) #2589 #2643 
 - [ ] Optional for bonus points [0.5]: Do an atomic cross chain swap with another blockchain. Ping us for support if needed
 - [x] Make a proposal and check the verbose output, and reject it #2499 #2527 
 - [x] Find the new Poll/BSIP section in voting panel and vote on something #2626
 - [x] Export both types for account activities #2543
 - [x] Cancel multiple orders in Exchange #2317

**Comment by froooze** [comment]
#2774
#2775
#2776
#2777
#2778
#2779
#2780
#2785
#2790
#2791
#2797
#2799
#2800
#2801
#2808
#2809
#2813
#2817
#2818
#2819
#2824
#2825
#2827

**Comment by sschiessl-bcp** [comment]
Include https://github.com/bitshares/bitshares-ui/issues/2769#issue-455489633 in here for bounty

**Comment by sschiessl-bcp** [comment]
Thanks for extensive testing. All issues accepted for bounty, even if some of them might be closed due to being duplicates. Keep up the good work!

**Comment by sschiessl-bcp** [comment]
Two integration tests plus 40 issues. Total bounty: 5
