### ISSUE TITLE
[3.1.190618-rc2] Integration Tests by [allfory0u] for Firefox 

### ISSUE THREAD

**Issue by allfory0u** [bitshares/bitshares-ui#2865]
My OS:
  - Windows 10

My Browser:
 - Firefox 67.0.4

General 
 - [x] Wallet loads and connects
 - [x] Login via cloud login and local wallet
 - [x] Transfer between accounts (with and without memo)
 - [x] Exchange opens, orders are visible and limit orders can be put
 - [x] Margin creation and adjustment is possible
 - [x] Voting is possible (committee, witness, proposals)

Specific components:
 - [x] Test HTCL functionality (create, extend and redeem) #2589 #2643 
   - [ ] Optional for bonus points [0.5]: Do an atomic cross chain swap with another blockchain. Ping us for support if needed
 - [x] Make a proposal and check the verbose output, and reject it #2499 #2527 
 - [x] Find the new Poll/BSIP section in voting panel and vote on something #2626
 - [x] Export both types for account activities #2543
 - [x] Cancel multiple orders in Exchange #2317

**Comment by allfory0u** [comment]
Testing in progress

**Comment by froooze** [comment]
Final release is already out!

**Comment by allfory0u** [comment]
> Final release is already out?

Not sure, but I already found some bugs in the testing process

**Comment by allfory0u** [comment]
Testing is complete

**Comment by sschiessl-bcp** [comment]
@froooze He approached me in telegram and I was happy to find someone willing to do extensive testing.

@allfory0u please make sure to link all issues you found during testing in here. Also please include #2880 #2883 and #2899 in here as a separate comment and close the other three issues.

**Comment by allfory0u** [comment]
#2880 - [3.1.190618-rc1] Integration Tests by [allfory0u] for Chrome 
#2883 - [3.1.190618.1] Integration Tests by [allfory0u] for Light Client 
#2899 - [3.1.190618.2-rc1] - Integration Tests by [allfory0u] for standard Android browser

**Comment by allfory0u** [comment]
#2940
#2939
#2926
#2925
#2922
#2921
#2914
#2913
#2912
#2893 
#2892
#2890
#2888
#2887
#2886
#2885
#2884
#2881
#2878
#2875
#2874
#2873
#2868
#2867
#2866

**Comment by allfory0u** [comment]
@sschiessl-bcp Done.

**Comment by allfory0u** [comment]
@sschiessl-bcp ping

**Comment by sschiessl-bcp** [comment]
> @sschiessl-bcp Done.

Sorry ... I missed that ping

**Comment by sschiessl-bcp** [comment]
Bounty:
- 4 integration tests: 2
- 40 issues created. Some of them were not applicable, or duplicates. Nevertheless, I am happy to have a reliable tester and want to motivate, so all accepted: 4

Total bounty: 6

**Comment by startailcoon** [comment]
Agree with @sschiessl-bcp, nice work @allfory0u on all your testings.

**Comment by allfory0u** [comment]
Thank you, @sschiessl-bcp and @startailcoon!
