### ISSUE TITLE
[3.1.190618.2-rc1] - Integration Tests by [allfory0u] for standart Android browser

### ISSUE THREAD

**Issue by allfory0u** [bitshares/bitshares-ui#2899]
My OS:
  - Android 5.1.1 (MIUI Global 7.2) / Android 9
  - Standart browser v10.4.5 / Chrome 75

General 
 - [x] Wallet loads and connects
 - [x] Login via cloud login and local wallet
 - [ ] Transfer between accounts (with and without memo)
 - [ ] Exchange opens, orders are visible and limit orders can be put
 - [ ] Margin creation and adjustment is possible
 - [ ] Voting is possible (committee, witness, proposals)

Specific components:
 - [ ] Test HTCL functionality (create, extend and redeem) #2589 #2643 
   - [ ] Optional for bonus points [0.5]: Do an atomic cross chain swap with another blockchain. Ping us for support if needed
 - [ ] Make a proposal and check the verbose output, and reject it #2499 #2527 
 - [ ] Find the new Poll/BSIP section in voting panel and vote on something #2626
 - [ ] Export both types for account activities #2543
 - [ ] Cancel multiple orders in Exchange #2317

**Comment by allfory0u** [comment]
#2912
