### ISSUE TITLE
[3.5][startailcoon] Refactor Open Orders

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#733]
In the Open Orders table it is not immediately clear which column stands for which asset of the two in the pair. "Qty" and "Total" are vague and the pairs can be inverted which flips them anyway so at quick glance there is some thinking the user has to do to figure it out. Sometimes it is obvious, sometimes not.

In other tables at exchanges I have seen the column headers "Amount", "Value", "Price", but it doesn't matter which words we use because it will still be vague due to the pairs being invertible.

I suggest adding the asset name as a unit next to the number. Instead of "29.00000" it could be "29.00000 BTS".

I realize this might quickly be a space issue as some names are longer and some numbers are big. I don't know how to solve that but one idea is to shrink the "Order Value" (should be called "Current Value" or simply "Value") column by removing the unit from the column header and placing it next to the number in each row just like we would have in the Qty and Total columns. The Order Value column is too wide, there is no reason for this aside from its long name. The name could even be reduced to "Value" to save more space. "Order" is redundant as we are already in the "Open Orders" section so why use that word, it wastes space.

**Comment by landry314** [comment]
Solving this would solve issue #624 as well.

It is generally confusing which columns mean what in the Open Orders section... we could solve this all at once.

**Comment by startailcoon** [comment]
I can take this task

**Comment by wmbutler** [comment]
Should I move this into 171119?

**Comment by startailcoon** [comment]
Leave this for the milestone as it is. Thanks

**Comment by wmbutler** [comment]
I think your arrow direction switch is too subtle for most people to notice. What if we **bold** the appropriate asset instead?

**Comment by startailcoon** [comment]
Definitely need some more, ofcourse. The arrow is just one thing. Still thinking of a good way to do it. I'm reluctant to add any `buy/sell` text as it would bloat the table.

I will post an update on some more changes we can make later this week.

**Comment by startailcoon** [comment]
I've updated this to set the assets in the color if they are bid or buy,

In the following liceCap I'm Buying 10 GRC for 1 BTS at 0.1 GRC/BTS.
*In reverse this means we're Selling 1 BTS for 10 GRC at 10 GRC/BTS.*

BTS: Selling = Red
GRC: Buy = Green

- Arrow Direction always heading towards the assets you're buying.
- Selling asset is always red
- Buying asset is always green

![bitshares-tradingpair-openorders_2](https://user-images.githubusercontent.com/12114550/33804697-a175f270-ddaa-11e7-9e52-d5d249f034b8.gif)

**Comment by svk31** [comment]
I like where this is going, but to be honest even to me it's not obvious what's what in the QTY and TOTAL columns.

Not sure what to do about it though, I tested with a bottom border in the QTY and TOTAL fields indicating sell/bid but it got too messy.

Perhaps another column with 'Buy BTS', 'Sell BTS' etc, indicating exactly what the order is for in the current market direction.

**Comment by svk31** [comment]
![image](https://user-images.githubusercontent.com/6890015/33825781-0c155338-de63-11e7-8232-6a938433497e.png)

**Comment by startailcoon** [comment]
I like what your saying here as well. My change made it a little bit more clear, but we neee a bit more.

I'll have another look at it. Maybe @wmbutler can do some of his great mockups?

**Comment by wmbutler** [comment]
What if the arrows always face the same way, but the only thing that changes are the order of the pairs and the color? I think we have too many variables for a user to digest.

**Comment by startailcoon** [comment]
What if we do it like this @wmbutler 

Type|Base|Quote|Cost|Value (bitUSD)|Trade|Cancel
-|-|-|-|-|-|-
Buy|1 bitUSD for 2 BTS|1.3 BTS/bitUSD|2.6 BTS|1 bitUSD|[ ]|[ ]
Sell|2 BTS for 1 bitCNY|0.4 bitCNY/BTS|0.2 bitCNY|1 bitUSD|[ ]|[ ]

Where `Quote` can be inverted as we do on activity history tab. Quote will then be the ONLY field that changes.

The type, base and cost is based on the order, what we're looking for is only what the order would be in the opposite direction.

Value is based on the default asset as we have today, and is only an example.

**Comment by wmbutler** [comment]
What is we put units `BTS/bitUSD` in it's own column since otherwise it forces us to repeat it in the quote and price column?

Type|Quantity|Quote|Price|Units|Value (bitUSD)|Trade|Cancel
-|-|-|-|-|-|-|-
Buy|2 bitUSD|1.3|2.6|BTS/bitUSD|1|[ ]|[ ]
Sell|0.2 BTS|0.4|0.8| bitCNY/BTS|1|[ ]|[ ]

Notable changes:

- [ ] Replace Amount with Quantity
- [ ] Display units in a separate column
- [ ] Change Amount to Quantity since Quantity more accurately describes units
- [ ] A bit out of scope, but it would be awesome to use our pulse feature on the Quote value reinforcing that this is a live quote.

**Comment by startailcoon** [comment]
How about this then?

I find this much easier to understand.

```
Row 1: A buy order of 10 open.GRC for 1 BTS at the price of 0.1 BTS - Current Market at 0.26...
Row 2: A Sell order of 12 open.GRC for 12 BTS at the price of 1 BTS - Current market at 0.26...
Row 3: A buy order of 4 BTS for 1 bitUSD at the price of 0.25 bitUSD - Current market at 0.42...
Row 4: A buy order of 4 BTS for 1.04 bitUSD at the price of 0.26 bituSD - Current market at 0.42...
Row 5: A sell order of 2.301 BTS for 1 bitUSD at the price of 0.4346 bitUSD - Current market at 0.42...
```

I've removed the possibility to revert the order book, and if the user reverts the asset in another section of the wallet it will disregard this. It could be enabled, just looking if the asset is flipped and turn everything around. Personally I find this unnecessary, do we need this?

![image](https://user-images.githubusercontent.com/12114550/34073333-b45d2f10-e297-11e7-87d8-cb5c6285e087.png)

I will not do this now:
> A bit out of scope, but it would be awesome to use our pulse feature on the Quote value reinforcing that this is a live quote.

**Comment by svk31** [comment]
There's a bit too much coloring now. I suggest you remove the colors from the last two columns, and instead color the buy / sell text.

We definitely need to keep the market direction flipping, people prefer different directions and we have no wsy of knowing which one they used to place the order.

**Comment by landry314** [comment]
Are we going to change "Order Value (bitUSD)" to "Value" then put the unit next to the value in the row? This makes it easier to read and will shorten the length of the column to save space. Having to look up to the top of a column to see the unit is a waste of time. Also, looking at the table in https://github.com/bitshares/bitshares-ui/issues/733#issuecomment-352202045 above we see units next to most values anyway. It fits.

**Comment by startailcoon** [comment]
![screenshot from 2017-12-16 22-26-43](https://user-images.githubusercontent.com/12114550/34074477-3b662472-e2b0-11e7-8f6c-afd98ac2abc4.png)

**Comment by landry314** [comment]
Last time I will say this, but, still, I think "Order Value" is not clear. Is it the current value of the assets stuck in this order or the value or the order at the time it is executed? See? I know it is the current value because I have been talking about this for months... but your average user might not understand and have to figure it out. Why not just call it "Current Value" and then it is clear? The word "order" is not helpful because it is in the "Open Orders" section and hence we all know we are dealing with an order. That word is meaningless, takes up space, and provides less value (haha) than the word "Current" would. How can anyone argue against this? I have been ignored and told it didn't matter or was clear the way it was, but no one has actually refuted this argument. Why not use a word that makes it clear rather than a redundant word that just takes up space??? Sigh.

**Comment by startailcoon** [comment]
Please see the latest version update

@landry314 I'm not sure whether anyone ignored you or not, but I've missed your comment about it and agree with you on it. I've modified the header to your suggestions. 

- [x] Renamed `Order Value` to `Value` 
- [x] Aligned `TOTAL (ASSET)` to the right to better align with the `Value` column
- [x] Buy/Sell properly set, hopefully. Please notify me if anything odd shows up.


![bitshares-tradingpair-openorders_](https://user-images.githubusercontent.com/12114550/34080967-8911d086-e346-11e7-882b-a1106ea0a7a5.gif)

**Comment by wmbutler** [comment]
- [ ] Maybe since we have the "trade" column, you can let the click invert the price without the "Go To Market" tooltip.

**Comment by svk31** [comment]
I'm not convinced the current status is an improvement, with the lack of right alignment and asset names all over it's pretty disorganised. Look at  these two before/after screens for example:

![image](https://user-images.githubusercontent.com/6890015/34120790-1e3c92dc-e427-11e7-85bf-faa8a03320f9.png)

![image](https://user-images.githubusercontent.com/6890015/34120818-398b04a6-e427-11e7-9ae7-28763d195c9a.png)

**Comment by startailcoon** [comment]
With that many orders I do agree with @svk31 , it looks jumbled.

Two proposals on a fix.

Right Aligned
![rigthaligned](https://user-images.githubusercontent.com/12114550/34124958-15e40f94-e435-11e7-8591-d333aacdd771.png)

Right + Left Aligned
![leftalign](https://user-images.githubusercontent.com/12114550/34124956-15b6e654-e435-11e7-9ac5-badff379b7ec.png)

**Comment by wmbutler** [comment]
I think this has digressed. Really having a hard time understanding the direction we are going here.

**Comment by wmbutler** [comment]
Type|Quantity|Price|Value|Quote|Trade|Cancel
-|-|-|-|-|-|-
Buy|2 bitUSD|for 2.6 BTS/bitUSD|1|2.3|[ ]|[ ]
Sell|0.2 BTS|for 0.8 bitCNY/BTS|1|0.7|[ ]|[ ]

**Comment by startailcoon** [comment]
> Really having a hard time understanding the direction we are going here.

Same here, honestly.
I will make a new update based on your last post.

**Comment by wmbutler** [comment]
+1 hour

**Comment by startailcoon** [comment]
After some changes; here's an update 

# Current View
![trading_before](https://user-images.githubusercontent.com/12114550/34352696-556e2768-ea24-11e7-8838-1f560a71a068.PNG)

# After Change
![trading_after](https://user-images.githubusercontent.com/12114550/34352705-60355252-ea24-11e7-856d-cc2802bdd52b.PNG)

The old view had one column for each asset in the trade (QTY and TOTAL), which I think confuses many users.

# Proposed with Market Price
What the new view doesn't have is the current market price, and I think we could be able to fit that nicely as shown below.

![trading_after_withmarketprice](https://user-images.githubusercontent.com/12114550/34352786-d1fca58e-ea24-11e7-805e-dbef8425b93e.PNG)

## TODO
I think the only thing left now is to find a good alignment of the columns.
Please advice if you think any more changes is nessesary.

**Comment by wmbutler** [comment]
I'm really sorry about all the confusion here. Sometimes, I feel completely unqualified for this. As I look over my own statements, I feel like I'm mixing units and causing confusion. The second and third columns should probably have whole units and just occupy a single column. That would make the sentence flow smoothly.

As a matter of fact, we could combine Type/Qty/Price into "Description"

Description|Price|Market Price|Value|Trade|Cancel
-|-|-|-|-|-
Buy 2 bitUSD for 4 BTS|2|2.3|2|[ ]|[ ]

**Comment by startailcoon** [comment]
![image](https://user-images.githubusercontent.com/12114550/34362273-5f1c7758-ea72-11e7-8049-447380fc9f92.png)

Not sure if the Flip icon is in the best place, but I think it's getting there now. Flip will reveal the opposite assets `Price` and `Market Price`

**Comment by wmbutler** [comment]
This is looking pretty good:

- [ ] I'd remove the flip column and let the user click on the description to flip it
- [ ] Add the Cancel Column back (we lost that somewhere in this work, there is cancel and filter logic that you possibly never pulled in I suppose)
- [ ] Left justify the Description

**Comment by startailcoon** [comment]
Cancel column isn't gone, just that I'm not viewing my own account.

Clicking in the `Description` column now flips the order. It's not obvious that it does this though. We could make the whole row enable flipping (except the trade button of course).

Here's a large liceCap of the whole thing.

![bitshares-openorders](https://user-images.githubusercontent.com/12114550/34362799-ec15fc5c-ea76-11e7-86c3-ec65fce7e1af.gif)

**Comment by wmbutler** [comment]
- [ ] I think the whole row as a click would be a great idea. I think this works!

**Comment by startailcoon** [comment]
Some cleanup and it's ready if none can think of something else.

![bitshares-openorders-2](https://user-images.githubusercontent.com/12114550/34363699-c5ccd9b4-ea7e-11e7-902a-794c0b8e3329.gif)

**Comment by wmbutler** [comment]
- [ ] Markets flip when clicking Trade and Cancel
- [ ] Pretty sure Price and Market Price should be the inverse of what they are relative to the Description

In the example below, I'd expect to be buying Open.EOS for BTS at a price of 12.

![screen shot 2017-12-28 at 11 16 08 am](https://user-images.githubusercontent.com/1254810/34417937-e644e6bc-ebc0-11e7-90f2-bf8d9603e456.png)
![screen shot 2017-12-28 at 11 15 51 am](https://user-images.githubusercontent.com/1254810/34417938-e6500722-ebc0-11e7-832a-de410118263f.png)

**Comment by startailcoon** [comment]
Fixed the issue with the Price and Market Price mismatch. 
I've tried to verify that it's correct, and can only see that it's correct now, but please do verify as well.

**Comment by wmbutler** [comment]
I tested, looks great!

**Comment by startailcoon** [comment]
Merged, Closing issue
